---
title: "내가 태어났을 때"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 내가 태어났을 때

내가 태어났을 때나는 울었고,내 주변의 모든 사람은웃고 즐거워하였다.

내가 내 몸을 떠날 때나는 웃었고,내 주변의 모든 사람은울며 괴로워하였다.

덧없는 삶에의 유혹으로부터벗어나라.자만심으로부터무지로부터어리석음의 광기로부터속박을 끊으라.

그때 비로소 그대는모든 괴로움으로부터완전히 자유로우리라.

생과 사의 사슬을 끊으라. 어리석은 삶으로 빠져드는 이치를 알고 그것을 끊어 버리라.

그때 비로소 그대는 이 지상의 삶에 대한 욕망으로부터 자유롭게 되어

고요하고 평온하게 그대의 길을 걸어가리라.

<티베트 사자의 서>에서

세상의 미친 자들

세상의 미친 자들에게 붙여지는 이름이 있다. 현실 부적응자, 반항아.문제아, 부적합 판정을 받은 자. 사물을 다른 각도에서 바라보는 자들, 이들은 규칙을 좋아하지 않는다. 그리고 현상 유지를 별로 존중하지 않는다.

당신은 그들의 말을 인용할 수 있고, 그들에게 동의하지 않을 수도 있고, 그들을 칭찬하거나 비난할 수 있다. 하지만 그들에 대해 당신이 할 수 없는 단 한 가지는 그들을 무시하는 일. 왜냐하면 그들은 사물을 바꿔 놓기 때문이다.

그들은 발명하고, 상상하고, 치료한다. 탐험하고, 창조하고, 영감을 불어넣는다. 그들은 인류를 앞으로 나아가게 만든다. 어쩌면 그들은 미쳐야만 하는지도 모른다.

그렇지 않고 어떻게 텅 빈 화폭에서 그림을 볼 수 있겠는가.어떻게 침묵 속에 앉아결코 씌어진 적이 없는 노래를 들을 수 있겠는가.또는 붉은 행성들을 응시하면서우주 정거장을 떠올릴 수 있겠는가.

어떤 사람들은 그들을 미치광이라 부르지만,우리는 그들을 천재라 부른다.세상을 바꿀 수 있다고 생각할 만큼 미친 사람들만이결국 세상을 바꿀 수 있기 때문에.

어느 고등학교 교사가 썼다고 전해지는 이 시는

애플 컴퓨터 사의 텔레비전 광고에 사용되었다.