---
title: "나는 누구인가"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 나는 누구인가

나는 누구인가. 그들이 종종 말하기를 나는 감방에서 걸어나올 때 마치 왕이 자기의 성에서 걸어나오듯 침착하고, 활기차고, 당당하다고 한다.

나는 누구인가. 그들이 종종 말하기를 나는 간수에게 말을 건넬 때 마치 내게 명령하는 권한이라도 있는 듯 자유롭고, 다정하고, 분명하다고 한다.

나는 누구인가. 그들이 또한 말하기를 나는 불행한 날들을 견디면서 마치 승리에 익숙한 자와 같이 평화롭고, 미소 지으며, 자연스럽다고 한다.

나는 정말 다른 이들이 말하는 그런 존재인가. 아니면 다만 나 자신이 알고 있는 자에 지나지 않는가.

새장에 갇힌 새처럼 불안하게 뭔가를 갈망하다 병이 들고 손들이 나의 목을 조르고 있는 듯 숨 가쁘게 몸부림치고 빛깔과 꽃들과 새소리를 갈구하며 부드러운 말과 인간적인 친근함을 그리워하고 사소한 모욕에도 분노로 치를 떠는,

그리고 위대한 사건들을 간절히 고대하고 저 멀리 있는 친구들을 그리워하다 힘없이 슬퍼하고 기도하고 생각하고 글쓰는 일에 지치고 텅 빈, 무기력하게 그 모든 것과 이별할 채비를 갖춘 그런 존재.

나는 누구인가. 이것인가, 저것인가. 오늘은 이런 인간이고 내일은 다른 인간인가. 아니면 동시에 둘 다인가. 타인 앞에서는 위선자이고, 자기 자신 앞에서는 경멸할 수밖에 없는 가련한 약자인가.

나는 누구인가. 이 고독한 물음이 나를 비웃는다.

하지만 내가 누구이든, 신은 안다.내가 그의 것임을.

나치에 항거하던 행동주의 신학자 디트리히 본회퍼가

베를린 감옥에서 숨을 거두기 전에 쓴 시

뒤에야

고요히 앉아 본 뒤에야 평상시의 마음이 경박했음을 알았네. 침묵을 지킨 뒤에야 지난날의 언어가 소란스러웠음을 알았네.. 일을 돌아본 뒤에야 시간을 무의미하게 보냈음을 알았네. 문을 닫아건 뒤에야 앞서의 사귐이 지나쳤음을 알았네. 욕심을 줄인 뒤에야 이전의 잘못이 많았음을 알았네. 마음을 쏟은 뒤에야 평소에 마음씀이 각박했음을 알았네..

중국 명나라 문인 진계유

세례를 위한 시

물속으로 들어가라.물이 네 갈증을 달래 줄 테니.네 삶의 흐름 속으로 너를 데려다 줄 테니.

불을 꿈꾸라.불이 네 몸을 덥혀 줄 테니.불꽃이 네 영혼에 빛을 비출 테니..

별들을 바라보라.성운들이 네 안에서 돌고 있는원자들처럼 끝없이 회전할 테니..

나무에 대해 말하라.나무가 지상에서 하늘을 향해 솟아오를 테니.마치 너의 척추처럼.

남자들과 여자들은 너를 둘러싸고숨과 목소리들이너의 것과 서로 섞이리라.

홀로 너는 아무것도 아니지만 모두 함께 살아가리라.

가브리엘 꾸장

단 하나의 삶

어느 날 당신은 알게 되었다. 자신이 무엇을 해야만 하는지. 그리고 마침내 그 일을 시작했다. 주위의 목소리들이 계속해서 잘못된 충고를 외쳐댔지만 집 식구들은 불안해 하고 과거의 손길이 발목을 붙잡았지만 저마다 자신의 인생을 책임지라고 소리쳤지만 당신은 멈추지 않았다. 자신이 무엇을 해야만 하는지 알고 있었기에.

거센 바람이 불어와 당신의 결심을 흔들고 마음은 한없이 외로웠지만, 시간이 이미 많이 늦고 황량한 밤, 길 위에는 쓰러진 나뭇가지와 돌들로 가득했지만 조금씩 앞으로 나아가는 동안 어둔 구름들 사이로 별들이 빛나기 시작했다.

그리고 어떤 목소리가 들려왔다. 당신이 세상 속으로 걸어가는 동안 언제나 당신을 일깨워 준 목소리. 당신이 할 수 있는 단 하나의 일이 무엇인지 당신이 살아야 할 단 하나의 삶이 무엇인지를.

메리 올리버