---
title: "나는 배웠다"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 나는 배웠다.

나는 배웠다.

다른 사람으로 하여금 나를 사랑하게 만들 수 없다는 것을.

내가 할 수 있는 일은 사랑받을 만한 사람이 되는 것뿐임을.

사랑은 사랑하는 사람의 선택에 달린 일.

나는 배웠다.

내가 아무리 마음을 쏟아 다른 사람을 돌보아도

그들은 때로 보답도 반응도 하지 않는다는 것을.

신뢰를 쌓는 데는 여러 해가 걸려도

무너지는 것은 한순간임을.

삶은 무엇을 손에 쥐고 있는가가 아니라

누가 곁에 있는가에 달려 있음을 나는 배웠다.

우리의 매력이라는 것은 15분을 넘지 못하고

그 다음은 서로를 알아가는 것이 더 중요함을.

다른 사람의 최대치에 나를 비교하기보다는

나 자신의 최대치에 나를 비교해야 함을 나는 배웠다.

삶은 무슨 사건이 일어나는가에 달린 것이 아니라

일어난 사건에 어떻게 대처하는가에 달린 것임을.

또 나는 배웠다.

무엇을 아무리 얇게 베어 낸다 해도 거기에는 언제나 양면이 있다는 것을.

그리고 내가 원하는 사람이 되는 데는 오랜 시간이 걸린다는 것을.

사랑하는 사람에게는 언제나 사랑의 말을 남겨 놓아야 함을 나는 배웠다.

어느 순간이 우리의 마지막 시간이 될지 아는 사람은 아무도 없으므로,

두 사람이 서로 다툰다고 해서

서로 사랑하지 않는 게 아님을 나는 배웠다.

그리고 두 사람이 서로 다투지 않는다고 해서

서로 사랑하는 게 아니라는 것도.

두 사람이 한 가지 사물을 바라보면서도 보는 것은 완전히 다를 수 있음을.

나는 배웠다.

나에게도 분노할 권리는 있으나

타인에 대해 몰인정하고 잔인하게 대할 권리는 없음을.

내가 바라는 방식대로 나를 사랑해 주지 않는다 해서 내 전부를 다해 사랑하지 않아도 좋다는 것이 아님을.

그리고 나는 배웠다.

아무리 내 마음이 아프다 하더라도 이 세상은 내 슬픔 때문에 운행을 중단하지 않는다는 것을.

타인의 마음에 상처를 주지 않는 것과 내가 믿는 것을 위해 내 입장을 분명히 하는 것, 이 두 가지를 엄격하게 구분하는 일이 얼마나 어려운가를.

나는 배웠다.

사랑하는 것과 사랑받는 것을.

트라피스트 수도회 출신으로 예수의 작은 형제회를 설립한 샤를르 드 푸코의 작품으로 알려져 있지만 많은 이들이 자신의 시라고 주장하고 있다.

침묵의 소리

존재의 언어로 만나자.부딪침과 느낌과 직감으로,

나는 그대를 정의하거나 분류할 필요가 없다.그대를 겉으로만 알고 싶지 않기에.침묵 속에서 나의 마음은그대의 아름다움을 비춘다.그것만으로도 충분하다.

소유의 욕망을 넘어그대를 만나고 싶은 그 마음그 마음은있는 그대로의 우리를 허용해 준다.

함께 흘러가거나 홀로 머물거나 자유다.나는 시간과 공간을 초월해그대를 느낄 수 있으므로,

클라크 무스타카스

생명은

자기 자신만으로는 완성될 수 없도록 만들어져 있는 듯하다.

꽃도

암술과 수술이 갖추어져 있는 것만으로는 불충분하며, 곤충이나 바람이 찾아와 암술과 수술을 중매한다. 생명은 그 안에 결핍을 지니고 있으며 그것을 다른 존재로부터 채워 받는다.

세계는 아마도 다른 존재들과의 연결 그러나 서로가 결핍을 채운다고는 알지도 못하고 알려지지도 않고 그냥 흩어져 있는 것들끼리 무관심하게 있을 수 있는 관계 때로는 마음에 들지 않은 것들도 허용되는 사이 그렇듯 세계가

느슨하게 구성되어 있는 것은 왜일까.

꽃이 피어 있다.바로 가까이까지곤충의 모습을 한 다른 존재가빛을 두르고 날아와 있다.

나도 어느 때누군가를 위한 곤충이었겠지.당신도 어느 때나를 위한 바람이었겠지.

요시노 히로시