---
title: "삶을 위한 지침"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 삶을 위한 지침

다른 사람들이 기대하는 것보다 더 많이, 그리고 진심으로 기뻐하며 주라. 자신이 가장 좋아하는 시를 외우라. 들리는 모든 것을 믿지는 말라. 때로 자신이 갖고 있는 모든 것을 써버려라, 아니면 실컷 잠을 자라.

첫눈에 반하는 사랑을 믿으라. 다른 사람의 꿈을 절대로 비웃지 말라, 꿈이 없는 사람은 가난한 사람이니까. 사랑은 깊고 열정적으로 하라. 상처받을 수도 있지만, 그것만이 완전한 삶을 사는 유일한 길이다.

위대한 사랑과 위대한 성취는 엄청난 위험을 동반한다는 사실을 기억하라. 실패하더라도, 그것을 통해 배움을 얻는 일에까지 실패하지는 말라.

때로는 침묵이 가장 좋은 해답이 될 수 있음을 기억하라. 변화하는 데 인색하지 말라. 그러나

자신의 가치관을 지키라.. 무엇보다 바람직하고 존경할 만한 삶을 살라. 늙어서 자신의 생을 돌아볼 때 또다시 그것을 살게 될 테니까.

신을 믿으라, 하지만 차는 잠그고 다니라. 숨은 뜻을 알아차리라. 당신의 지식을 남과 나누라, 그것이 영원한 삶을 얻는 길이므로, 기도하라, 헤아릴 수 없이 많은 힘이 거기에 있다.

자신이 실수한 것을 깨닫는 순간, 즉시 바로잡으라. 즐겁게 대화를 나눌 수 있는 사람과 결혼하라, 늙으면 그것이 아주 중요해질 테니까. 하지만 가끔 혼자 있는 시간을 가지라..

일 년에 한 번은, 전에 전혀 가보지 않았던 곳을 찾아가라. 돈을 많이 벌었다면 살아 있을 때 다른 사람을 돕는 데 쓰라, 그것이 부가 가져다주는 가장 큰 만족이다.

자신이 원하는 걸 얻지 못하는 것이 때로는 큰 행운일 수 있다는 점을 기억하라.

규칙을 배우고 나서, 그중 몇 가지를 위반하라. 무엇을 얻기 위해 무엇을 포기했는가를 자신의 성공을 평가하는 기준으로 삼으라. 자신의 성격이 곧 자신의 운명임을 기억하라.

작자 미상. 처음에는 〈행운을 가져다주는 네팔 탄트라 토템) 또는

〈달라이 라마의 만트라〉라는 제목으로 알려진 시