---
title: "우리 시대의 역설"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 우리 시대의 역설

건물은 높아졌지만 인격은 더 작아졌다. 고속도로는 넓어졌지만 시야는 더 좁아졌다. 소비는 많아졌지만 더 가난해지고 더 많은 물건을 사지만 기쁨은 줄어들었다.

집은 커졌지만 가족은 더 적어졌다. 더 편리해졌지만 시간은 더 없다. 학력은 높아졌지만 상식은 부족하고 지식은 많아졌지만 판단력은 모자라다. 전문가들은 늘어났지만 문제는 더 많아졌고 약은 많아졌지만 건강은 더 나빠졌다.

너무 분별없이 소비하고 너무 적게 웃고 너무 빨리 운전하고 너무 성급히 화를 낸다.

너무 많이 마시고 너무 많이 피우며 너무 늦게까지 깨어 있고 너무 지쳐서 일어나며 너무 적게 책을 읽고, 텔레비전은 너무 많이 본다.

116

그리고 너무 드물게 기도한다.

가진 것은 몇 배가 되었지만 가치는 더 줄어들었다. 말은 너무 많이 하고 사랑은 적게 하며 거짓말은 너무 자주 한다.

생활비를 버는 법은 배웠지만 어떻게 살 것인가는 잊어버렸고 인생을 사는 시간은 늘어났지만 시간 속에 삶의 의미를 넣는 법은 상실했다.

달에 갔다 왔지만 길을 건너가 이웃을 만나기는 더 힘들어졌다. 외계를 정복했는지 모르지만 우리 안의 세계는 잃어버렸다. 공기 정화기는 갖고 있지만 영혼은 더 오염되었고 원자는 쪼갤 수 있지만 편견을 부수지는 못한다.

자유는 더 늘었지만 열정은 더 줄어들었다. 키는 커졌지만 인품은 왜소해지고

117

이익은 더 많이 추구하지만 관계는 더 나빠졌다.세계 평화를 더 많이 얘기하지만 전쟁은 더 많아지고여가 시간은 늘어났어도 마음의 평화는 줄어들었다.

더 빨라진 고속 철도더 편리한 일회용 기저귀더 많은 광고 전단그리고 더 줄어든 양심쾌락을 느끼게 하는 더 많은 약들그리고 더 느끼기 어려워진 행복.

제프 딕슨이 처음 인터넷에 이 시를 올린 뒤, 많은 사람들이

한 줄씩 덧보태 지금도 이어지고 있다.

118

도의 사람

도 안에서 걸림 없이 행동하는 사람은 그 자신의 이해에 얽매이지 않으며 또 그런 개인적인 이해에 얽매여 있는 사람을 경멸하지도 않는다. 그는 재물을 모으고자 애쓰지 않으며 그렇다고 청빈의 덕을 내세우지도 않는다. 그는 남에게 의존함 없이 자신의 길을 걸어가며 또한 홀로 걸어감을 자랑하지도 않는다. 대중을 따르지 않으면서도 대중을 따르는 자를 비난하지 않는다. 어떤 지위와 보상도 그의 마음을 끌지 못하며 불명예와 부끄러움도 그의 길을 가로막지 못한다. 그는 매사에 옳고 그름을 판단하지 않으며, 긍정과 부정에 좌우되지도 않는다. 그런 사람을 도의 사람이라 부른다.

장자. 토머스 머튼 번역

119

그럼에도 불구하고

사람들은 때로 믿을 수 없고, 앞뒤가 맞지 않고, 자기중심적이다. 그럼에도 불구하고 그들을 용서하라.

당신이 친절을 베풀면 사람들은 당신에게 숨은 의도가 있다고 비난할 것이다. 그럼에도 불구하고 친절을 베풀라.

당신이 어떤 일에 성공하면 몇 명의 가짜 친구와 몇 명의 진짜 적을 갖게 될 것이다. 그럼에도 불구하고 성공하라.

당신이 정직하고 솔직하면 상처받기 쉬울 것이다. 그럼에도 불구하고 정직하고 솔직하라.

오늘 당신이 하는 좋은 일이내일이면 잊혀질 것이다. 그럼에도 불구하고 좋은 일을 하라.

가장 위대한 생각을 갖고 있는 가장 위대한 사람일지라도

120

가장 작은 생각을 가진 작은 사람들의 총에 쓰러질 수 있다. 그럼에도 불구하고 위대한 생각을 하라.

사람들은 약자에게 동정을 베풀면서도 강자만을 따른다. 그럼에도 불구하고 소수의 약자를 위해 싸우라.

당신이 몇 년을 걸려 세운 것이 하룻밤 사이에 무너질 수도 있다. 그럼에도 불구하고 다시 일으켜 세우라.

당신이 마음의 평화와 행복을 발견하면 사람들은 질투를 느낄 것이다. 그럼에도 불구하고 평화롭고 행복하라.

당신이 가진 최고의 것을 세상과 나누라. 언제나 부족해 보일지라도, 그럼에도 불구하고 최고의 것을 세상에 주라.

인도 캘커타의 마더 테레사 본부 벽에 붙어 있는 시

121