---
title: "의족을 한 남자"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 의족을 한 남자

한쪽 다리에 의족을 한 남자가

감옥을 탈출하다가 붙잡혔다.

간수들은 그의 의족을 빼앗아 버렸다.

날마다 그는 한쪽 다리를 한 채로

언덕을 넘고 강을 건너

밭에 가서 강제 노동을 해야만 했다.

일 년이 지나 크리스마스 이브가 되자

간수들은 그의 의족을 돌려주었다.

하지만 그에게는 더 이상 의족이 필요 없었다.

그는 이미 완벽한 탈출 계획을 세웠기에.

한쪽 다리로 탈출하는 계획을.

제임스 테이트

사이치에게 남은 것

사이치에게 남은 것은 아무것도 없네.

기쁨에 가득 찬 심장 말고는

그에게 남은 것은 아무것도 없네.

좋은 것도 나쁜 것도 없이

모든 것이 그에게서 떠나갔네.

남은 것은 아무것도 없네.

아무것도 갖지 않음.

얼마나 완벽한 만족인가..

아사하라 사이치

이제 난 안다.

내가 사과 세 알만한 꼬마였을 때 난 사나이가 되기 위해 큰 소리로 외치곤 했지. 난 알아, 난 알아, 난 다 알고 있다구!'

그것이 시작이었고, 그때가 바로 인생의 봄하지만 열여덟 살이 되었을 때 난 또다시 말했지. '난 알아, 이번에는 진짜로 알아."

그리고 오늘, 지난 일들을 회상하는 날들 중에 내가 수없이 걸어온 길들을 되돌아보네. 그 길들이 어디서 와서 어디로 가는지 난 아직도 알지 못하네.

스물다섯 살 무렵 나는 모든 걸 알았었지. 사랑과 열정, 삶과 돈에 대해. 그중에서도 사랑에 대해서라면 모든 걸 다 해봤지.

생의 한가운데서 난 또 다른 배움을 얻었지. 내가 배운 것은 서너 마디로 말할 수 있다네. 어느 날 누군가 당신을 사랑하고 날씨마저 좋다면

'정말 날씨 한번 좋다' 라고밖에 더 잘 말할 수 없다는 것을.

생의 가을녘에 들어선 내게 아직도 삶에서 경이로운 것은 그토록 많았던 슬픈 저녁들은 잊혀지지만 어느 행복했던 아침은 결코 잊혀지지 않는다는 것.

젊은 시절 내내 '난 알아' 하고 말하고 싶었지만 그 답을 찾으면 찾을수록 알게 되는 건 더 적었지.

지금 내 인생의 괘종시계가 60번을 울렸고 난 아직 창가에 서 있지. 밖을 내다보면서 난 자문해 보네. 그리고 이제서야 난 알 수 없다는 것을 깨달았지. 삶과 사랑, 돈과 친구들, 그리고 열정에 대해.. 그것들이 가진 소리와 색에 대해 결코 알 수 없다는 것을.

이것이 바로 내가 알고 있는 것의 전부. 하지만 바로 그것을 난 또 알고 있지.

장 가방

누가 떠나고 누가 남는가

위대한 사람들의 무덤을 바라볼 때내 마음속 시기심은 모두 사라져 버린다.미인들의 묘비명을 읽을 때무절제한 욕망은 덧없어진다.

아이들 비석에 새겨진 부모들의 슬픔을 읽을 때내 마음은 연민으로 가득해진다.하지만 그 옆에 있는 부모들 자신의 무덤을 볼 때곧 따라가 만나게 될 사람을 슬퍼하는 것이얼마나 헛된 일인가를 깨닫는다.

쫓겨난 왕들이 그들을 쫓아낸 사람들 옆에묻혀 있는 것을 볼 때또 온갖 논리와 주장으로 세상을 갈라놓던학자와 논객들이 나란히 묻힌 것을 볼 때인간의 하잘것없는 다툼, 싸움, 논쟁에 대해나는 슬픔과 놀라움에 젖는다.

조지프 애디슨, 웨스트민스터 대성당에서 쓴 시

내가 알고 있는 것

내가 무엇을 행하고 있는지나는 알고 있는가. 내가 나를 소유하는 순간은 숨을 들이마시는 동안인가, 아니면 내쉬는 동안인가. 내가 알고 있는 것은 다음에 무엇을 쓸지 연필이 알고 있는 정도, 또는 다음에 어디로 갈지그 연필심이 짐작하는 정도.

잘랄루딘 루미