---
title: "힘과 용기의 차이"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 힘과 용기의 차이

강해지기 위해서는 힘이 필요하고 부드러워지기 위해서는 용기가 필요하다.

자신을 방어하기 위해서는 힘이 방어 자세를 버리기 위해서는 용기가

이기기 위해서는 힘이 져주기 위해서는 용기가

확신을 갖기 위해서는 힘이 필요하고 의문을 갖기 위해서는 용기가 필요하다.

조화를 이루기 위해서는 힘이 전체의 뜻에 따르지 않기 위해서는 용기가

다른 사람의 고통을 느끼기 위해서는 힘이 자신의 고통과 마주하기 위해서는 용기가 필요하다.

자신의 감정을 숨기기 위해서는 힘이 필요하고 그것을 표현하기 위해서는 용기가 필요하다.

128

학대를 견디기 위해서는 힘이 필요하고 그것을 중단시키기 위해서는 용기가 필요하다.

홀로 서기 위해서는 힘이 필요하고 누군가에게 기대기 위해서는 용기가 필요하다.

사랑하기 위해서는 힘이 사랑받기 위해서는 용기가

생존하기 위해서는 힘이 삶을 살기 위해서는 용기가 필요하다.

데이비드 그리피스

129

일일초

오늘도 한 가지슬픈 일이 있었다.오늘도 또 한 가지기쁜 일이 있었다.

웃었다가 울었다가희망했다가 포기했다가미워했다가 사랑했다가

그리고 이런 하나하나의 일들을부드럽게 감싸 주는헤아릴 수 없이 많은평범한 일들이 있었다.

호시노 도미히로, 교사 시절 기계 체조를 가르치다가

철봉에서 떨어져 전신마비가 됨

130

- 

하나, 둘, 세 개의 육체

나는 단 하나의 육체를 갖고 있지만 두 개의 영혼을 갖고 있지. 하나는 감동하기 위해 다른 하나는 냉정하기 위해. 나는 단 하나의 영혼을 갖고 있지만 두 개의 육체를 갖고 있지. 하나는 지속되기 위해 다른 하나는 사라지기 위해.하지만 또 나는 세 개의 영혼을 갖고 있지. 순결하고 순결하지 못한, 그리고 정화해야 할 또 다른 하나를. 나는 세 개의 육체를 갖고 있지. 진실과 거짓의 그리고 상상 속의.. 또 나는 더 이상 육체도 영혼도 갖고 있지 않지.

알랭 보스께

131