---
title: "그런 사람"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 그런 사람

집착 없이 세상을 걸어가고아무것도 가진 것 없이자기를 다스릴 줄 아는 사람모든 속박을 끊고괴로움과 욕망이 없는 사람미움과 잡념과 번뇌를 벗어던지고맑게 살아가는 사람거짓도 없고 자만심도 없고어떤 것을 내 것이라 주장하지도 않는 사람이미 강을 건너 물살에 휩쓸리지 않는 사람

이 세상이나 저 세상이나 어떤 세상에 있어서도삶과 죽음에 걸림이 없는 사람모든 욕망을 버리고 집 없이 다니며다섯 가지 감각을 안정시켜달이 월식에서 벗어나듯이 붙들리지 않는 사람모든 의심을 넘어선 사람자기를 의지처로 하여 세상을 다니고모든 일로부터 벗어난 사람이것이 마지막 생이고

122

더 이상 태어남이 없는 사람고요한 마음을 즐기고 생각이 깊고, 언제 어디서나 깨어 있는 사람

인도 고대 경전 숫타니파타〉 중에서

123

빛

모든 인간 존재로부터는하늘로 똑바로 올라가는한 줄기 빛이 나온다.함께 있기로 운명지어진두 영혼이 서로를 발견하는 순간두 빛줄기는 하나가 된다.그렇게 해서 하나가 된 두 존재로부터는더 밝은 한 줄기의 빛이비쳐 나온다.

바알 셈 토브

124

또 다른 충고들

고통에 찬 달팽이를 보게 되거든 충고하려 들지 말라. 그 스스로 고통에서 벗어나올 것이다. 너의 충고는 그를 화나게 하거나 상처 입게 만들 것이다. 하늘의 선반 위로 제자리에 있지 않은 별을 보게 되거든 그럴 만한 이유가 있을 것이라고 생각하라. 더 빨리 흐르라고 강물의 등을 떠밀지 말라. 풀과 돌, 새와 바람, 그리고 대지 위의 모든 것들처럼 강물은 나름대로 최선을 다하고 있는 것이다. 시계추에게 달의 얼굴을 가지고 있다고 말하지 말라. 너의 말이 그의 마음을 상하게 할 것이다. 그리고 너의 문제들을 가지고 너의 개를 귀찮게 하지 말라. 그는 그만의 문제들을 가지고 있으니까.

장 루슬로

125

태양의 돌

죽은 자는 스스로의 죽음 속에 묶여 다시 달리 죽을 수 없다. 스스로의 모습 속에 못박혀 다시 어쩔 도리가 없다. 그 고독으로부터, 그 죽음으로부터 별수 없이 보이지 않는 눈으로 우리를 지켜볼 뿐 그의 죽음은 이제 그의 삶의 동상거기 항상 있으면서 항상 있지 않은. 우리는 하나의 삶의 기념비 우리 것이 아닌 우리가 살지 않는 남의 삶.

그러니까 삶이라는 것이 언제 정말 우리의 것인 일이 있는가. 언제 우리는 정말 우리 자신인가. 잘 생각해 보면 우리는 아무것도 아니다. 아무것도 되어 본 일이 없다. 삶은 한 번도 우리 것인 적이 없다. 그건 언제나 남의 것. 삶은 아무의 것도 아니다. 우리 모두가 삶이고, 남을 위해 태양으로 빚은 빵 우리 모두 남인 우리라는 존재. 내가 존재할 때 나는 남이다. 나의 행동은 나의 것만이 아니라 우리 모두의 것이기도 하다.

126

내가 존재하기 위해서 나는 남이 되어야 한다. 내게서 떠나와 남들 사이에서 나를 찾아야 한다. 남들이란 결국 내가 존재하지 않으면 존재하지 않는 것 그 남들이 나의 존재를 가능하게 한다. 나는 존재하지 않는다. 내가 없다. 항상 우리다. 삶은 항상 다른 것. 항상 거기 있는 것, 멀리 있는 것, 너를 떠나 나를 떠나 항상 지평선으로 남아 있는 것. 우리의 삶을 앗아가고 우리를 타인으로 남겨 놓는 삶 우리에게 얼굴을 만들어 주고 그 얼굴을 마모시키는 삶.

옥타비오 빠스

127