---
title: "신을 믿는 것"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 신을 믿는 것

아무런 열정도 마음의 갈등도 불확실한 것도, 의심도 심지어는 좌절도 없이 신을 믿는 사람은 신을 믿는 것이 아니다. 그는 다만 신에 관한 생각을 믿고 있을 뿐이다.

미구엘 드 우나무도

98

회교 사원 벽에 씌어진 시

구차하게 사느니 죽음을 택하라. 남의 비위를 맞추느니 적은 것에 만족하라. 어차피 자신의 것이 아니면 어떤 방법을 써도 자신의 것이 되지 않을 터. 운명에는 이틀이 있다. 하루는 당신의 편, 다른 하루는 당신에게 등을 돌리리라.. 그러므로 운명이 자신의 편일 때 자만하거나 무모하지 말며, 운명이 등을 돌릴 때 참고 기다리라. 모든 자랑거리를 내려놓고 늘 자신의 무덤을 기억하라. 그것을 거부하는 자는 진리에 의해 쓰러질 것이니. 가슴은 진정한 깨달음의 책, 머리의 영리함을 잊고 오래 서 있는 나무처럼 자유에 대한 갈망을 견디라. 그것이 진정한 이해에 이르는 길이니.

하드라트 알리

90

사막의 지혜

강이 있었다.그 강은 머나먼 산에서 시작해 마을과 들판을 지나마침내 사막에 이르렀다.

강은 곧 알게 되었다.사막으로 들어가기만 하면

자신의 존재가 사라져 버린다는 것을.

그때 사막 한가운데에서 어떤 목소리가 들려왔다."바람이 사막을 건널 수 있듯이강물도 건널 수 있다.'

강은 고개를 저었다.사막으로 달려가기만 하면강물이 흔적도 없이 모래 속으로 사라져 버린다고.바람은 공중을 날 수 있기에문제없이 사막을 건널 수 있는 것이라고,

사막의 목소리가 말했다.'그 바람에게 너 자신을 맡겨라.

100

너를 증발시켜 바람에 실어라.'

하지만 두려움 때문에 강은차마 자신의 존재를 버릴 수가 없었다.그때 문득 어떤 기억이 떠올랐다.언젠가 바람의 팔에 안겨 실려가던 일이.

그리하여 강은 자신을 증발시켜바람의 다정한 팔에 안겼다.바람은 가볍게 수증기를 안고 날아올라수백 리 떨어진 건너편 산꼭대기에 이르러살며시 대지에 비를 떨구었다.

그래서 강이 여행하는 법은사막 위에 적혀 있다는 말이 전해지게 되었다. .

수피(이슬람 신비주의) 우화시

101

어부의 기도

주님, 저로 하여금 죽는 날까지물고기를 잡을 수 있게 하시고,마지막 날이 찾아와당신이 던진 그물에 내가 걸렸을 때바라옵건대 쓸모없는 물고기라 여겨내던져짐을 당하지 않게 하소서.

17세기, 작자 미상

102

당신의 손에 할 일이 있기를

당신 손에 언제나 할 일이 있기를. 당신 지갑에 언제나 한두 개의 동전이 남아 있기를. 당신 발 앞에 언제나 길이 나타나기를. 바람은 언제나 당신의 등 뒤에서 불고 당신의 얼굴에는 해가 비치기를. 이따금 당신의 길에 비가 내리더라도 곧 무지개가 뜨기를. 불행에서는 가난하고 축복에서는 부자가 되기를. 적을 만드는 데는 느리고 친구를 만드는 데는 빠르기를. 이웃은 당신을 존중하고 불행은 당신을 아는 체도 하지 않기를. 당신이 죽은 것을 악마가 알기 30분 전에 이미 당신이 천국에 가 있기를. 앞으로 겪을 가장 슬픈 날이 지금까지 겪은 가장 행복한 날보다 더 나은 날이기를. 그리고 신이 늘 당신 곁에 있기를.

켈트 족 기도문

103