---
title: "초대"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 초대

당신이 생존을 위해 무엇을 하는가는내게 중요하지 않다.당신이 무엇 때문에 고민하고 있고,자신의 가슴이 원하는 것을 이루기 위해어떤 꿈을 간직하고 있는가 나는 알고 싶다.

당신이 몇 살인가는 내게 중요하지 않다.나는 다만 당신이 사랑을 위해진정으로 살아 있기 위해주위로부터 비난받는 것을두려워하지 않을 자신이 있는가 알고 싶다.

어떤 행성 주위를 당신이 돌고 있는가는 중요하지 않다.당신이 슬픔의 중심에 가닿은 적이 있는가삶으로부터 배반당한 경험이 있는가그래서 잔뜩 움츠러든 적이 있는가또한 앞으로 받을 더 많은 상처 때문에마음을 닫은 적이 있는가 알고 싶다.

나의 것이든 당신 자신의 것이든

당신이 기쁨과 함께할 수 있는가 나는 알고 싶다.미친 듯이 춤출 수 있고, 그 환희로손가락 끝과 발가락 끝까지 채울 수 있는가당신 자신이나 나에게 조심하라고, 현실적이 되라고,인간의 품위를 잃지 말라고주의를 주지 않고서 그렇게 할 수 있는가.

당신의 이야기가 진실인가 아닌가는 중요하지 않다.당신이 다른 사람들을 실망시키는 한이 있더라도자기 자신에게는 진실할 수 있는가배신했다는 주위의 비난을 견디더라도자신의 영혼을 배신하지 않을 수 있는가 알고 싶다.

어떤 것이 예쁘지 않더라도 당신이그것의 아름다움을 볼 수 있는가그것이 거기에 존재한다는 사실에서더 큰 의미를 발견할 수 있는가 나는 알고 싶다.

당신이 누구를 알고 있고 어떻게 이곳까지 왔는가는내게 중요하지 않다.

다만 당신이 슬픔과 절망의 밤을 지샌 뒤지치고 뼛속까지 멍든 밤이 지난 뒤 자리를 떨치고 일어날 수 있는가 알고 싶다.

나와 함께 불길의 한가운데 서 있어도 위축되지 않을 수 있는가 모든 것이 떨어져 나가더라도 내면으로부터 무엇이 당신의 삶을 지탱하고 있는가

그리고 당신이 자기 자신과 홀로 있을 수 있는가 고독한 순간에 자신과 함께 있는 것을 진정으로 좋아할 수 있는가 알고 싶다.

오리아 마운틴 드리머