---
title: "무사의 노래"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 무사의 노래

나에겐 부모가 없다 하늘과 땅이 나의 부모나에겐 집이 없다. 깨어 있음이 나의 집나에겐 삶과 죽음이 없다. 숨이 들고 나는 것이 나의 삶과 죽음나에겐 특별한 수단이 없다. 이해가 나의 수단나에겐 힘이 없다. 정직이 나의 힘나에겐 비밀이 없다 인격이 나의 비밀나에겐 몸이 없다. 인내가 곧 나의 몸나에겐 눈이 없다. 번개의 번쩍임이 나의 눈나에겐 귀가 없다. 예민함이 나의 귀나에겐 팔다리가 없다. 신속함이 나의 팔다리

나에겐 기적이 없다.

바른 행동이 나의 기적나에겐 고정된 원칙이 없다. 모든 상황에 적응하는 것이 나의 원칙나에겐 전략이 없다. 비움과 채움이 나의 전략나에겐 벗이 없다. 내 외로운 마음이 곧 나의 벗나에겐 적이 없다. 부주의가 곧 나의 적나에겐 갑옷이 없다. 관대함과 의로움이 나의 갑옷나에겐 굳건한 성이 없다. 흔들림 없는 마음이 나의 성나에겐 검이 없다. 나를 버림이 곧 나의 검

15세기 일본 무사들의 노래

사랑

끊임없이 자신을 비우기에 언제나 새로우며

최상의 호기심으로 배움에 임하지만 결코 지식을 쌓지 않으며

무엇이 되려고 한 적이 없기에 없음이라고 불리며

끝이 없이 깊고 닿지 않는 곳이 없으며

앎의 세계로부터 벗어나 있기에 모름이라고 불리며

그의 힘은 무한하나 한없이 부드러우며

보지 않는 구석이 없고 듣지 않는 소리가 없으며

그의 덕은 높고도 크나

겸손은 한없이 낮으며

우리의 사고가 끝나는 곳 단어의 의미가 끝나는 곳에서

어쩌면 만날 수도 있는 그것은 실체로서의 사랑

지두 크리슈나무르티

실

네가 따르는 한 가닥 실이 있다. 그 실은 변화하는 것들 사이로 지나간다. 하지만 그 실은 변하지 않는다. 사람들은 네가 무엇을 따라가는지 궁금해 할 것이다. 너는 그 실에 대해 설명해야만 한다. 그러나 사람들에게는 잘 보이지 않는다. 그 실을 붙잡고 있는 한 너는 길을 잃지 않는다. 비극은 일어나기 마련이고, 사람들은 상처 입거나 죽는다. 그리고 너는 고통받고 늙어간다. 시간이 하는 일을 너는 어떻게도 막을 수 없다. 그래도 그 실을 절대로 놓지 말라.

윌리엄 스태포드

자연에게서 배운 것

여기 전에 알지 못하던 어떤 분명하고 성스런 약이 있어 오직 감각뿐이던 내게 분별력이 생겨신이 그러하듯 사려 깊고 신중해진다.

전에는 듣지 못하던 귀와 보지 못하던 눈에 이제는 들리고 보인다. 세월을 살던 내가 순간을 살고 배운 말만 알던 내가 이제는 진리를 안다.

소리 너머의 소리를 듣고 빛 너머의 빛을 본다. 태양이 그 빛을 잃을 만큼.

헨리 데이빗 소로우, 월든 숲에서 쓴 시