---
title: "선택의 가능성들"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 선택의 가능성들

영화를 더 좋아한다. 강가의 떡갈나무들을 더 좋아한다. 인류를 사랑하는 자신보다 인간을 사랑하는 자신을 더 좋아한다. 만일의 경우에 대비해 실이 꿰어진 바늘을 갖고 다니는 것을 더 좋아한다. 초록색을 더 좋아한다. 모든 것을 비난하는 것이 곧 이성적인 판단이라고 주장하지 않는 것을 더 좋아한다. 예외를 더 좋아한다. 일찍 떠나기를 더 좋아한다. 의사와 다른 일에 대해 이야기하기를 더 좋아한다. 세밀한 선으로 그린 오래된 그림을 더 좋아한다. 시를 쓰지 않을 때의 어리석음보다. 시를 쓸 때의 어리석음을 더 좋아한다. 해마다 맞이하는 특별한 기념일이 아닌 사랑으로 모든 날들을 기념하는 것을 더 좋아한다. 내게 아무것도 약속하지 않지만 도덕적인 사람을 더 좋아한다. 너무 쉽게 믿는 친절보다.

사려 깊은 친절을 더 좋아한다. 정복하는 나라보다 정복당하는 나라를 더 좋아한다. 약간 주저하는 것을 더 좋아한다. 질서 잡힌 지옥보다 혼돈의 지옥을 더 좋아한다. 신문의 제1면보다 동화를 더 좋아한다. 잎이 없는 꽃보다 꽃이 없는 잎들을 더 좋아한다. 꼬리의 일부를 잘라 내지 않은 개를 더 좋아한다. 내 눈이 짙은색이기 때문에 옅은색 눈을 더 좋아한다. 서랍들을 더 좋아한다. 여기에 말한 많은 것들보다 여기에 말하지 않은 많은 것들을 더 좋아한다. 별들의 시간보다 벌레들의 시간을 더 좋아한다. 나무를 두드리는 것을 더 좋아한다. 얼마나 더 오래, 그리고 언제라고 묻지 않는 것을 더 좋아한다. 모든 존재가 그 자신만의 존재 이유를 갖고 있다는 가능성을 마음에 담아 두는 것을 더 좋아한다.

비슬라바 쉼보르스카

89

태초에 여자가 있었으니

첫째날, 내가 추위에 몸을 떨며 캄캄한 암흑 속으로 나아가 잔가지들을 주워 모아 모닥불을 피웠을 때 그분께서 덜덜 떨며 동굴 밖으로 나와 모닥불에 손을 쬐면서 말씀하시기를 '빛이 있으라' 하셨다.

둘째날, 내가 새벽부터 일어나 강에서 물을 길어다가 그분의 얼굴에 먼지가 묻지 않도록 마당에 물을 뿌렸을 때 그분께서 밖으로 나와 내가 손바닥에 부어 주는 물로 얼굴을 씻고 나서 하늘을 올려다보며 말씀하시기를 '지붕 위를 하늘이라 부르고, 마른 곳을 땅이라 부르며, 물은 바다에 모이게 하자' 하셨다.

셋째날, 내가 일찌감치 일어나 열매들을 따 모으고 작은 씨앗들을 두 돌멩이 사이에 넣고 갈아 반죽을 만들고 빵을 구웠을 때 그분께서 기지개를 켜며 일어나 빵과 열매들을 드시면서 말씀하시기를 '땅으로 하여금 풀과 채소와 각종 씨 맺는 열매들을

0

키우게 하자' 하셨다.

넷째날, 내가 허둥지둥 일어나 잎사귀 달린 나뭇가지로마당을 쓸고, 빨랫감을 물에 담그고, 단지들을 문지르고 연장들을 닦고, 자루 달린 긴 낫을 숫돌에 갈고 있을 때 그분께서 느지막이 일어나 말씀하시기를 '하늘에 빛이 있어 그 빛으로 낮과 밤을 나누자' 하셨다.

다섯째날, 내가 아침부터 뛰어다니며 구유를 채우고 말에게 건초를 주고, 양털을 깎고, 거위를 배불리 먹이고 염소들에게 풀을 뜯기고, 암탉들에게 줄 옥수수를 갈고 오리들 먹일 쐐기풀을 베고, 돼지 먹일 부엌 찌끼를 데우고, 소젖을 짜고, 고양이에게 우유를 부어 주었을 때 그분께서 길게 하품을 하고 눈에서 잠을 부벼 내며 말씀하시기를 "모든 생물로 하여금 번성하여 땅을 뒤덮게 하자' 하셨다.

여섯째날, 찌르는 통증에 잠을 깬 내가 아이를 낳고 몸을 씻기고, 포대기로 싸고, 젖을 먹였을 때 그분께서 아이를 들여다보며 아이의 작은 손이

91

자신의 엄지손가락을 잡게 하시고 자기를 닮은 아이의 얼굴을 보고 미소 지으며 말씀하시기를 '내가 지은 모든 것이 참으로 보기에 좋더라' 하셨다.

일곱째날, 아이의 울음소리에 잠이 깬 나는 서둘러 기저귀를 갈고 젖을 먹여 달랜 뒤, 불을 켜고 창문을 열어 실내를 환기시키고, 신문을 가져오고 식물들에게 물을 주고, 조용히 청소를 한 뒤 아침을 만들었다. 그때, 커피 내음에 잠이 깬 그분께서 텔레비전을 켜고 담배에 불을 붙이며 말씀하시기를 "일곱째날은 쉬자' 하셨다.

1999년 독일 프랑크푸르트 국제 도서전에서 '가장 아름다운 책'으로 선정된

에바 토트의 시집에 실린 시

92

내가 엄마가 되기 전에는

내가 엄마가 되기 전에는 언제나 식기 전에 밥을 먹었었다.

얼룩 묻은 옷을 입은 적도 없었고 전화로 조용히 대화를 나눌 시간이 있었다.

내가 엄마가 되기 전에는 원하는 만큼 잠을 잘 수 있었고 늦도록 책을 읽을 수 있었다. 날마다 머리를 빗고 화장을 했다.

날마다 집을 치웠었다. 장난감에 걸려 넘어진 적도 없었고, 자장가는 오래전에 잊었었다. 내가 엄마가 되기 전에는 어떤 풀에 독이 있는지 신경 쓰지 않았었다. 예방 주사에 대해선 생각도 하지 않았었다.

누가 나한테 토하고, 내 급소를 때리고 침을 뱉고, 머리카락을 잡아당기고 이빨로 깨물고, 오줌을 싸고

3

손가락으로 나를 꼬집은 적은 한 번도 없었다.

엄마가 되기 전에는 마음을 잘 다스릴 수가 있었다. 내 생각과 몸까지도. 울부짖는 아이를 두 팔로 눌러 의사가 진찰을 하거나 주사를 놓게 한 적이 없었다. 눈물 어린 눈을 보면서 함께 운 적이 없었다. 단순한 웃음에도 그토록 기뻐한 적이 없었다. 잠든 아이를 보며 새벽까지 깨어 있었던 적이 없었다.

아이가 깰까봐 언제까지나 두 팔에 안고 있었던 적이 없었다. 아이가 아플 때 대신 아파 줄 수가 없어서 가슴이 찢어진 적이 없었다. 그토록 작은 존재가 그토록 많이 내 삶에 영향을 미칠 줄 생각조차 하지 않았었다. 내가 누군가를 그토록 사랑하게 될 줄 결코 알지 못했었다.

내 자신이 엄마가 되는 것을

4

그토록 행복하게 여길 줄 미처 알지 못했었다. 내 몸 밖에 또 다른 나의 심장을 갖는 것이 어떤 기분일지 몰랐었다. 아이에게 젖을 먹이는 것이 얼마나 특별한 감정인지 몰랐었다.

한 아이의 엄마가 되는 그 기쁨, 그 가슴 아픔, 그 경이로움, 그 성취감을 결코 알지 못했었다. 그토록 많은 감정들을. 내가 엄마가 되기 전에는,

작자 미상

95

예수가 인터넷을 사용했는가

산상수훈을 설파하기 위해 예수가 인터넷을 사용했는가. 자신의 복음을 널리 전파하기 위해 예수가 스팸 메일을 사용했는가.

사도 바울은 성능 좋은 메모리와 업 버전을 사용했는가. 그의 편지들은 바울로마 컴이라는 이메일 명으로 성경 게시판에 올려졌는가. 마케도니아에서 떠날 때 그는 문자 메시지로'가도 되는가'를 묻고 출발했는가.

모세는 바다를 가르기 위해 전자 게임기의 조종간을 작동했는가. 그리고 어디로 가야 할지를 알기 위해 위성 추적 장치의 도움을 받았는가. 그는 십계명을 손으로 썼는가, 아니면 영구히 보관되도록 CD에 기록했는가.

예수는 어느 날 나무 위에서 정말로 우리를 위해 죽었는가.

1. 

아니면 그것은 단지 홀로그램인가, 또는 컴퓨터 합성인가. 그것은 무선 인터넷을 통해 동영상으로 다운로드 받을 수 있는가.

만일 당신의 삶에서 신의 목소리를 듣기 어렵다면, 다른 목소리들이 너무 많이 들려 신의 목소리가 당신 귀에 가닿지 않는다면, 그렇다면 당신의 노트북 컴퓨터와 인터넷과 다른 모든 멋진 도구들을 내려놓으라. 그리고 순수함으로 돌아가라. 그러면 신이 당신 곁에 있으리라.

작자 미상. 로마 가톨릭 교황청 홈페이지에 오른 시

97