---
title: "사막"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 사막

그 사막에서 그는 너무도 외로워 때로는 뒷걸음질로 걸었다. 자기 앞에 찍힌 발자국을 보려고.

오르텅스 블루

파리 지하철 공사에서 공모한 시 콩쿠르에서 8천 편의 응모작 중 1등 당선된 시

게

동해 바다 작은 섬 갯바위의 흰 백사장 나 눈물에 젖어게와 놀았다네.

이시카와 다쿠보쿠

자살하려고 바닷가에 나갔다가 흰 모래사장 위의 작은 바닷게 한 마리에 눈이 팔려 그 게와 놀다가 자살할 마음도 잊다.

농담

문득 아름다운 것과 마주쳤을 때 지금 곁에 있으면 얼마나 좋을까 하고 떠오르는 얼굴이 있다면 그대는 사랑하고 있는 것이다.

그윽한 풍경이나 제대로 맛을 낸 음식 앞에서 아무도 생각하지 않는 사람 그 사람은 정말 강하거나 아니면 진짜 외로운 사람이다.

종소리를 더 멀리 보내기 위하여 종은 더 아파야 한다.

이문재

옹이

흉터라고 부르지 말라 한때는 이것도 꽃이었으니 비록 빨리 피었다 졌을지라도 상처라고 부르지 말라 한때는 눈부시게 꽃물을 밀어올렸으니 비록 눈물로 졌을지라도

죽지 않을 것이면 살지도 않았다. 떠나지 않을 것이면 붙잡지도 않았다. 침묵할 것이 아니면 말하지도 않았다. 부서지지 않을 것이면, 미워하지 않을 것이면 사랑하지도 않았다.

옹이라고 부르지 말라 가장 단단한 부분이라고 한때는 이것도 여리디 여렸으니다만 열정이 지나쳐 단 한 번 상처로 다시는 피어나지 못했으니

류시화

이별

당신의 부재가 나를 관통하였다. 마치 바늘을 관통한 실처럼. 내가 하는 모든 일이

그 실 색깔로 꿰매어진다.

윌리엄 스탠리 모원

나의 시

이것은 내가 읽을 수 있는 유일한 시나는 그 시를 쓸 수 있는 유일한 시인 모든 게 엉망이었을 때도 나는 자살하지 않았다. 약물에 의존하려고도 가르침을 얻으려고도 하지 않았다. 대신 나는 잠을 자려고 애썼다. 하지만 아무리 애써도 잠이 오지 않을 때는 시 쓰는 법을 배웠다. 바로 오늘 같은 밤 바로 나 같은 누군가가 읽을지도 모를 이런 시를 위해.

레너드 코헨