---
title: "축복의 기도"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 축복의 기도

11

이제 또 한 사람의 여행자가 우리 곁에 왔네. 그가 우리와 함께 지내는 날들이 웃음으로 가득하기를. 하늘의 따뜻한 바람이 그의 집 위로 부드럽게 불기를. 위대한 정령이 그의 집에 들어가는 모든 이들을 축복하기를. 그의 모카신 신발이 여기저기 눈 위에 행복한 발자국을 남기기를.

체로키 족 인디언들의 아이의 탄생을 축복하는 기도

모카신은 인디언들의 들소 가죽 신발

132

춤

나는 당신에게 초대장을 보냈다.내 손바닥에 삶의 불꽃으로 쓴 초대장을.

내게 보여 달라.아픔 속 아픔으로 나선형을 그리며 떨어지면서도당신이 당신의 가장 깊은 바람을 어떻게 따르고 있는가를.그러면 내가 날마다 어떻게 내면에 가닿고,또한 바깥을 향해 문을 열어 삶의 신비의 입맞춤을어떻게 내 입술에 느끼는가를 말해 줄 테니.

당신의 가슴속에 온 세상을 담고 싶다고 말하지 말라.다만 당신이 상처를 받고 사랑받지 못하는 것이 두려웠을 때어떻게 자신을 버리지 않고또 다른 실수를 저지르는 일로부터 등을 돌렸는가 말해 달라.

당신이 누구인지 알 수 있도록 내게 삶의 이야기를 들려 달라.그리고 내가 살아온 이야기들 속에서내가 진정 누구인가를 보아 달라.내게 말하지 말라.언젠가는 멋진 일들이 일어날 것이라고.

133

그 대신 마음의 흔들림 없이 위험과 마주할 수 있는가를 내게 보여 달라. 지금 이 순간 일어나는 모든 일들을 진정으로 받아들일 수 있는가를.

영웅적인 행동을 한 전사 같은 이야기는 충분히 들었다. 하지만 벽에 부딪쳤을 때 당신이 어떻게 무너져 내렸는가, 당신의 힘만으론 도저히 넘을 수 없었던 벽에 부딪쳤을 때 무엇이 당신을 벽 건너편으로 데려갔는가를 내게 말해 달라. 무엇이 자신의 연약한 아름다움을 느끼게 해주었는가를.

당신에게 춤추는 법을 가르쳐 준 그 장소들로나를 데려가 달라. 세상이 당신의 가슴을 부수려고 했던 그 위험한 장소들로, 그러면 나는 내 발 아래 대지와 머리 위 별들이 내 가슴을 다시 온전하게 만들어 준 장소들로 당신을 데려가리라.

함께 나누는 고독의 긴 순간들 속에 내 옆에 앉으라.

134

우리의 어쩔 수 없는 홀로 있음과또한 거부할 수 없는 함께 있음으로,침묵 속에서, 그리고 날마다 나누는 작은 말들 속에서나와 함께 춤을 추라.

우리 모두를 존재 속으로 내쉬는 위대한 들숨과그 영원한 정지 속에서나와 함께 춤을 추라.그 공허감을 바깥의 어떤 것으로도 채우지 말고다만 내 손을 잡고, 나와 함께 춤을 추라.

오리아 마운틴 드리머

135