---
title: "한 방울의 눈물"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 한 방울의 눈물

어느 날 나는 어떤 울음소리를 들었다. 자동차들의 소음 위로, 처음에 나는 그것이 새의 울음이나 어린 야생 동물의 울음이라 여겼다. 하지만 나는 길에 떨어진 내 가슴의 울음을 발견했다.

나는 울고 있는 나의 부서진 가슴을 주워 옷 속에 넣었다. 그것을 따뜻하게 보호하기 위해.

사람들은 집 잃은 어린 여우나 야생 늑대, 날개가 부러진 새를 보호했다가 그것들이 다 자라면 상처가 다 나으면 언덕으로 데리고 가 풀어 준다. 자유롭게 날고 자유롭게 뛰어다닐 수 있도록.

나도 내 가슴을 잘 보호하리라.

1. 

그것이 성장하고 치유될 때까지.그리하여 어느 날 그것을 언덕으로 데려가자유롭게 놓아주리라.그것이 내 머리 위 하늘로 날아가는 걸 보기 위해풀밭을 달려가는 걸 보기 위해.

그날 내 두 눈에는단 한 방울의 눈물만 남으리라.

레니타 드리저

105

옳은 말

아이를 잃은 엄마가 쓴 시

제발 내가 그것을 극복했는지 묻지 말아 주세요.난 그것을 영원히 극복하지 못할 테니까요..

지금 그가 있는 곳이 이곳보다 더 낫다고 말하지 말아 주세요..그는 지금 내 곁에 없으니까요.

상 그가 고통받지 않을 거라고는 말하지 말아 주세요.그가 고통받았다고 난 생각한 적이 없으니까요.

내가 느끼는 것을 당신도 알고 있다고는 말하지 말아 주세요.당신 또한 아이를 잃었다면 모를까요.

내게 아픔에서 회복되기를 빈다고 말하지 말아 주세요.잃은 슬픔은 병이 아니니까요.

내가 적어도 그와 함께 많은 해들을 보냈다고는 말하지 말아주세요.당신은, 당신의 아이가 몇 살에 죽어야 한다는 건가요?

내게 다만 당신이 내 아이를 기억하고 있다고만 말해 주세요.

106

만일 당신이 그를 잊지 않았다면,

신은 인간에게 극복할 수 있는 만큼의 형벌만 내린다고는 말하지 말아 주세요. 다만 내게 가슴이 아프다고만 말해 주세요.

내가 내 아이에 대해 말할 수 있도록 단지 들어만 주세요. 그리고 내 아이를 잊지 말아 주세요.

제발 내가 마음껏 울도록 지금은 다만 나를 내버려둬 주세요.

리타 모란

107

진정한 여행

가장 훌륭한 시는 아직 씌어지지 않았다.가장 아름다운 노래는 아직 불려지지 않았다.최고의 날들은 아직 살지 않은 날들가장 넓은 바다는 아직 항해되지 않았고가장 먼 여행은 아직 끝나지 않았다.불멸의 춤은 아직 추어지지 않았으며가장 빛나는 별은 아직 발견되지 않은 별무엇을 해야 할지 더 이상 알 수 없을 때그때 비로소 진정한 무엇인가를 할 수 있다.어느 길로 가야 할지 더 이상 알 수 없을 때그때가 비로소 진정한 여행의 시작이다.

나짐 히크메트, 감옥에서 쓴 시

108

나이

누군가 나에게 나이를 물었지.세월 속에 희끗희끗해진 머리를 보고 난 뒤내 이마의 주름살들을 보고 난 뒤.난 그에게 대답했지.내 나이는 한 시간이라고,사실 난 아무것도 세지 않으니까.게다가 내가 살아온 세월에 대해서는.그가 나에게 말했지.지금 무슨 말씀을 하시는 거죠? 설명해 주세요.그래서 난 말했지.어느 날 불시에 나는 내 마음을 사로잡은 이에게입을 맞추었지.아무도 모르는 은밀한 입맞춤을.나의 날들이 너무도 많지만나는 그 짧은 순간만을 세지.왜냐하면 그 순간이 정말로 나의 모든 삶이었으니까.

이븐 하짐.

1. 

죽음이 집에서 나를 기다린다.

죽음이 오늘 내 앞에 있다. 병의 회복 같은 고통 뒤의 산책 같은

죽음이 오늘 내 앞에 있다. 몰약 향기 같은 바람 부는 날의 천막 아래 휴식 같은

죽음이 오늘 내 앞에 있다. 연꽃 향기 같은 취기의 웃음 속 휴식 같은

죽음이 오늘 내 앞에 있다. 비 온 뒤 걷는 길 같은 오랜 전쟁 뒤의 집으로의 귀가 같은

죽음이 오늘 내 앞에 있다. 구름 낀 하늘이 개는 것처럼

110

알지 못하는 어떤 것에의 열망 같은

죽음이 오늘 내 앞에 있다.오랜 속박의 긴 해들을 지나자신의 집을 다시 본 기쁨 같은

하라

모든 나쁜 것들을 잊고 행복에침묵을 사랑하는 그 나라에이를 때까지

삶에 지친 사람과 그의 영혼과의 대화B.C. 1900년 경 이집트 파피루스에 적힌 시

111

여섯 가지 참회

내가 생각해야만 하는데도 생각하지 않은 것과말해야만 하는데도 말하지 않은 것행해야만 하는데도 행하지 않은 것

그리고 내가 생각하지 말아야 하는데도 생각한 것과말하지 말아야 하는데도 말한 것행하지 말아야 하는데도 행한 것그 모든 것들을 용서하소서.

젠드 아베스타(기원전 6세기 경)

페르시아 조로아스터 경전의 기도문

1. 

구도자의 노래

살아 있는 동안 손님을 맞이하라.살아 있는 동안 경험 속으로 뛰어들고살아 있는 동안 삶을 이해하라.그대가 구원이라고 부르는 것은죽음이 오기 전에만 가능한 일살아 있는 동안 밧줄을 끊지 않는다면죽은 뒤에 어떻게 자유를 얻겠는가.육체가 썩은 다음에야영혼이 신과 결합될 수 있다는 것은크나큰 착각이 아닐 수 없다.지금 그를 발견하라.지금 그를 찾지 못한다면그대 갈 곳은 죽음의 도시뿐지금 이 자리에서 그와 하나가 되라.그러면 이다음에도 그와 하나가 되리라.

까비르

113

신과의 인터뷰

어느 날 나는 신과 인터뷰하는 꿈을 꾸었다.신이 말했다.'그래, 나를 인터뷰하고 싶다구?'내가 말했다.네, 시간이 있으시다면.

신이 미소 지으며 말했다.'나의 시간은 영원,내게는 충분한 시간이 있다.무슨 질문을 마음속에 품고 있는가?'

내가 물었다.'인간에게서 가장 놀라운 점이 무엇인가요?'

신이 대답했다.'어린 시절이 지루하다고 서둘러 어른이 되는 것그리고는 다시 어린 시절로 되돌아가기를 갈망하는 것

돈을 벌기 위해 건강을 잃어버리는 것그리고는 건강을 되찾기 위해 돈을 다 잃는 것

114

미래를 염려하느라 현재를 놓쳐 버리는 것그리하여 결국 현재에도 미래에도 살지 못하는 것

결코 죽지 않을 것처럼 사는 것그리고는 결코 살아 본 적이 없는 듯 무의미하게 죽는 것.

신이 나의 손을 잡았다.우리는 잠시 침묵에 잠겼다.그런 다음 내가 겸허하게 말했다.시간을 내주셔서 감사합니다.당신의 자식들에게 그 밖에 하실 말씀이 있으신가요?'

신이 미소 지으며 말했다.'내가 이곳에 있음을 기억하기를.언제나, 모든 방식으로.'

작자 미상

115