---
title: "삶이 하나의 놀이라면"
author: "Siyun Min"
date: "2020-10-29"
categories: [Book, poem]
---
# 삶이 하나의 놀이라면

삶이 하나의 놀이라면 이것이 그 놀이의 규칙이다. 당신에게는 육체가 주어질 것이다. 좋든 싫든 당신은 그 육체를 이번 생 동안 갖고 다닐 것이다.

당신은 삶이라는 학교에 등록할 것이다. 수업 시간이 하루 스물네 시간인 학교에. 당신은 그 수업을 좋아할 수도 있고 쓸모없거나 어리석은 것이라 여길 수도 있다. 하지만 충분히 배우지 못하면 같은 수업이 반복될 것이다. 그런 후에 다음 과정으로 나아갈 것이다. 당신이 살아 있는 한 수업은 계속되리라.

당신은 경험을 통해 배우리라. 실패는 없다. 오직 배움만이 있을 뿐. 실패한 경험은 성공한 경험만큼 똑같이 중요한 과정이므로,

'이곳' 보다 더 나은 '그곳'은 없다. 다른 사람들은 모두 당신을 비추는 거울이다.

어떤 삶을 만들어 나갈 것인가는 전적으로자신에게 달려 있다.필요한 해답은 모두 자신 안에 있다.

그리고 태어나는 순간당신은 이 모든 규칙을 잊을 것이다.

체리 카터 스코트

여행

길을 선택해야만 했을 때 나는 서쪽으로 난 길을 택했다.길은 유년기의 숲에서 성공의 도시로 이어져 있었다.

내 가방에는 지식이 가득했지만두려움과 무거운 것들도 들어 있었다.내가 가진 가장 소중한 재산은그 도시의 황금 문으로 들어가리라는 이상이었다.

도중에 나는 건널 수 없는 강에 이르렀고내 꿈이 사라지는 것만 같아 두려웠다.하지만 나무를 잘라 다리를 만들고 강을 건넜다.여행은 내가 계획한 것보다 더 오래 걸렸다.비를 맞아 몹시 피곤해진 나는 배낭의무거운 것들을 버리고 걸음을 재촉했다.

그때 나는 숲 너머에 있는 성공의 도시를 보았다.나는 생각했다.'마침내 난 목적지에 도착했어. 온 세상이 부러워할 거야!'도시에 도착했지만 문이 잠겨 있었다.문 앞에 있는 남자가 눈살을 찌푸리며 목쉰 소리로 말했다.

'당신을 들여보낼 수 없어. 내 명단에 당신의 이름이 없어.”

나는 울부짖고, 비명을 지르고, 발길질을 해댔다. 내 삶은 이제 끝이라는 생각이 들었다. 그때 처음으로 나는 고개를 돌려내가 걸어온 동쪽을 바라보았다. 그곳까지 오면서 내가 경험한 모든 일들을.

도시에 들어갈 순 없었지만 그것이 내가 승리하지 못했다는 뜻은 아니었다. 나는 강을 건너고, 비를 피하는 법을 스스로 배웠다. 그리고 무엇보다 마음을 여는 법을 배웠다. 때로는 그것이 고통을 가져다줄지라도.

나는 알았다, 삶은 단순히 생존하는 것 이상임을.나의 성공은 도착이 아니라 그 여정에 있음을.

낸시 함멜

이누이트 족의 노래

새벽이 밝아오고 태양이 하늘의 지붕 위로 올라올 때면내 가슴은 기쁨으로 가득 합니다.

겨울에 인생은 경이로 가득 차 있었습니다. 그러나 겨울이 내게 행복을 가져다주었습니까.

아니오, 나는 신발과 바닥창에 쓸 가죽을 구하느라늘 노심초사했습니다. 어쩌다 우리 모두가 사용할 만큼 가죽이 넉넉하다 해도 그렇습니다. 나는 늘 걱정을 안고 살았습니다.

여름에 인생은 경이로 가득 차 있었습니다. 그러나 여름이 나를 행복하게 했습니까.

아니오, 나는 순록 가죽과 바닥에 깔 모피를 구하느라늘 조바심쳤습니다. 그렇습니다, 나는 늘 걱정을 안고 살았습니다.

빙판 위의 고기잡는 구멍 옆에 서 있을 때 인생은 경이로 가득 차 있었습니다.

그러나 고기잡이 구멍 옆에서 기다리며 나는 행복했습니까.

아니오. 물고기가 잡히지 않을까봐나는 늘 내 약한 낚시 바늘을 염려했습니다. 그렇습니다. 나는 늘 걱정을 안고 살았습니다.

잔칫집에서 춤을 출 때 인생은 경이로 가득 차 있었습니다. 그러나 춤을 춘다고 해서 내가 더 행복했습니까.

아니오, 나는 내 노래를 잊어버릴까봐 늘 안절부절못했습니다. 그렇습니다. 나는 늘 걱정을 안고 살았습니다.

내게 말해 주세요, 인생이 정말 경이로 가득 차 있는지. 그래도 내 가슴은 아직 기쁨으로 가득 찹니다. 새벽이 밝아오고 태양이 하늘의 지붕 위로 올라올 때면,

이누이트 족 코퍼 지파의 전통적인 노래