---
title: "CFA Level 1 Financial Reporting and Analysis Subnote"
author: "Siyun Min"
date: "2021-05-01"
categories: [CFA]
---
# Financial Reporting and Analysis

# Learning Outcome Statement

## Introduction of Financial Statement Analysis

### 19.a - Describe the roles of financial reporting and financial statement analysis

- **The role of financial reporting** is **to provide** a variety of users **with useful information about a company's performance and financial position.**
- **The role of financial statement analysis** is **to use the data** from financial statements to support economic decisions.

### 19.b - Describe the roles of statement of financial position, statement of comprehensive income, statement changes in equity, and statement of cash flows in evaluating a company's performance and financial position.

- The statement of financial position (balance sheet) shows assets, liabilities, and owners' equity at a point in time.
- The statement of comprehensive income shows the results of a firm's business activities over the period, Revenues, the cost of generating those revenues, and the resulting profit or loss are presented on the income statement.
- The statement of changes in equity reports the amount and sources of changes in the equity owners' investment in the firm.
- The statement of cash flows shows the sources and uses of cash over the period.

### 19.c - Describe the importance of financial statement notes and supplementary information-including disclosures of accounting policies, methods, and estimates-and management's commentary.

- Important information about accounting methods, estimates, and assumptions is disclosed in the footnotes to the financial statements and supplementary schedules.
- These disclosures also contain information about segment results, commitments and contingencies, legal proceedings, acquisitions or divestitures, issuance of stock options, and details of employee benefit plans.
- Management's commentary (Management's Discussion and Analysis) contains an overview of the company and important information about business trends, future capital needs, liquidity, significant events, and significant choices of accounting methods requiring management judgment.

### 19.d - Describe the objective of audits of financial statements, the types of audit reports, and the importance of effect internal controls.

- The objective of audits of financial statements is to provide an opinion on the statements' fairness and reliability.
- The auditor's opinion gives evidence of an independent review of the financial statements that verifies that appropriate accounting principles were used, that standard auditing procedures where used to establish reasonable assurance that the statements contain no material errors, and that management's report on the company's internal controls has been reviewed.
- An auditor can issue an unqualified (clean) opinion if the statements are free from material omissions and errors, a qualified opinion that notes any exceptions to accounting principles, an adverse opinion if the statements are not presented fairly in the auditor's opinion, or a disclaimer of opinion if the auditor is unable to express an opinion.

### 19.e - Identify and describe information sources that analyst use in financial statement analysis besides annual financial statements and supplementary information.

- Along with the annual financial statements, important information sources for an analyst include a company's quarterly and semiannual reports, proxy statements, press releases, and earnings guidance, as well as information on the industry and peer companies from external sources.

### 19.f - Describe the steps in the financial statement analysis framework.

1. State the objective of the analysis.
2. Gather data.
3. Process the data.
4. Analyze and interpret the data.
5. Report the conclusions or recommendations.
6. Update the analysis.

## Financial Reporting Standards

### 20.a. Describe the objective of financial reporting and the importance of financial reporting standards in security analysis and valuation.

- The objective of financial statements if to provide economic decision makers with useful information about a firm's financial performance and changes in financial position.
- Reporting standards are designed to ensure that different firms' statements are comparable to one another and to narrow the range of reasonable estimates on which financial statements are based. This aids users of the financial statements who rely on them for information about the company's activities, profitability, and creditworthiness.

### 20.b. Describe the roles of financial reporting standard-setting bodies and regulatory authorities in establishing and enforcing reporting standards.

- Standard-setting bodies are private sector organizations that establish financial reporting standards. The two primary standard-setting bodies are the International Accounting Standard Board (IASB) and, in the United States, the Financial Accounting Standards Board (FASB).
- Regulatory authorities are government agencies that enforce compliance with financial reporting standards. Regulatory authorities include the Securities and Exchange Commission in the United States and the Financial Conduct Authority in the United Kingdom. Many National regulatory authorities belong to the International Organization of Securities Commissions.

### 20.c. Describe the International Accounting Standards Board's conceptual framework, including financial qualitative characteristics of financial reports, constraints on financial reports, and required reporting elements.

- The IFRS "Conceptual Framework for Financial Reporting" defines the fundamental and enhancing qualitative characteristics of financial statements, specifies the required reporting elements, and notes the constraints and assumptions involved in preparing financial statements.
    - The fundamental characteristics of financial statements are relevance and faithful representation. The enhancing characteristics include comparability, verifiability, timeliness, and understandability.
    - Elements of financial statements are assets, liabilities, and owners' equity (for measuring financial position) and income and expenses (for measuring performance).
    - Constraints on financial statement preparation include cost versus benefit and the difficulty of capturing non-quantifiable information in financial statements.
    - The two primary assumptions that underlie the preparation of financial statements are the accrual basis and the going concern assumption.

### 20.d. Describe general requirements for financial statements under International Financial Reporting Standards (IFRS).

- Required financial statements are the balance sheet, comprehensive income statement, cash flow statement, statement of changes in owners' equity, and explanatory notes.
- The general features of financial statements according to IAS No. 1 are:
    - Fair presentation
    - Going concern
    - Accrual accounting
    - Consistency
    - Materiality
    - Aggregation
    - No offsetting
    - Reporting frequency
    - Comparative information
- Other presentation requirements include a classified balance sheet and specific minimum information that must be reported in the notes and on the face of the financial statements.

### 20.e. Describe implications for financial analysis of alternative financial reporting systems and the importance of monitoring developments in financial reporting standards.

- An analyst should be aware of evolving financial reporting standards and new products and innovations that generate new types of transactions.

## Understanding Income Statements

### 21.a. Describe the components of the income statement and alternative presentation formats of that statement.

- The income statement shows an entity's revenues, expenses, gains and losses during a reporting period.
- A multi-step income statement provides a subtotal for gross profit and a single step income statement does not. Expenses on the income statement can be grouped by the nature of the expense items or by their function, such as with expenses grouped into cost of goods sold.

### 21.b. Describe general principles of revenue recognition and accounting standards for revenue recognition.

- Revenue is recognized when earned and expenses are recognized when incurred.
- Accounting standards identify a five-step process for recognizing revenue:
    1. Identify the contract(s) with a customer.
    2. Identify the performance obligations in the contract.
    3. Determine the transaction price.
    4. Allocate the transaction price to the performance obligations in the cantract.
    5. Recognize revenue when (or as) the entity satisfies a performance obligation.

### 21.c. Calculate revenue given information that might influence the choice of revenue recognition method.

- Information that can influence the choice of revenue recognition method includes progress toward completion of a performance obligation, variable considerations and their likelihood of being earned, revisions to contracts, and whether the firm is acting as a principal or an agent in a transaction.

### 21.d. Describe general principles of expenses recognition, specific expense recognition applications, and implications of expense recognition choices for financial analysis.

- The matching principle requires that firms match revenues recognized in a period with the expenses required to generate them. One application of the matching principle is seen in accounting for inventory, with cost of goods sold as the cost of units sold from inventory that are included in current-period revenue. Other costs, such as depreciation of fixed assets or administrative overhead, are period costs and are taken without regard to revenues generated during the period.
- Depreciation methods
    - Straight-line: Equal amount of depreciation expense in each year of the asset's useful life.
    - Declining balance: Apply a constant rate of depreciation to the declining book value until book value equals residual value.
- Inventory valuation methods
    - FIFO: Inventory reflects cost of most recent purchases, COGS reflects cost of oldest purchases.
    - LIFO: COGS reflects cost of most recent purchases, inventory reflects cost of oldest purchases.
    - Average cost: Unit cost equals cost of goods available for sale divided by total units available and is used for both COGS and inventory.
    - Specific identification: Each item in inventory is identified and its historical cost is used for calculating COGS when the item is sold.
- Intangible assets with limited lives should be amortized using a method that reflects the flow over time of their economic benefits. Intangible assets with indefinite lives (e.g., goodwill) are not amortized.
- Users of financial data should analyze the reasons for any changes in estimates of expenses and compare these estimates with those of peer companies.

### 21.e. Describe the financial reporting treatment and analysis for non-recurring items (including discontinued operations, unusual or infrequent items) and changes in accounting policies.

- Results of discontinued operations are reported below income from continuing operations, net of tax, from the date the decision to dispose of the operations is made. These results are segregated because they likely are non-recurring and do not affect future net income.
- Unusual or infrequent items are reported before tax and above income from continuing operations. An analyst should determine how "unusual" or "infrequent" these items really are for the company when estimating future earnings or firm value.
- Changes in accounting standards, changes in accounting methods applied, and corrections of accounting errors require retrospective restatement of all prior-period financial statements included in the current statement. A change in an accounting estimate, however, is applied prospectively (to subsequent periods) with no restatement of prior-period results.

### 21.f. Distinguish between the operating and non-operating components of the income statement.

- Operating income is generated from the firm's normal business operations. For a nonfinancial firm, income that results from investing or financing transactions is classified as non-operating income, while it is operating income for a financial firm since its business operations include investing in and financing securities.

### 21.g. Describe how earnings per share is calculated and calculate and interpret a company's earnings per share (both basic and diluted earnings per share) for both simple and complex capital structures.

- basic EPS = (net income - preferred dividends) / (weighted average number of common shares outstanding)
- When a company has potentially dilutive securities, it must report diluted EPS.
- For any convertible preferred stock, convertible debt, warrants, or stock options that are dilutive, the calculation of diluted EPS is
    - diluted EPS = [(net income - preferred dividends) + convertible preferred dividends + convertible debt interest(1 - t)] / (weighted average shares) + (shares from conversion of conv. pfd. shares + shares from conversion of conv. debt + shares issuable from stock options)

### 21.h. Distinguish between dilutive and antidilutive securities and describe the implications of each for the earnings per share calculation.

- A dilutive security is one that, if converted to its common stock equivalent, would decrease EPS. An antidilutive security is one that would not reduce EPS if converted to its common stock equivalent.

### 21.i. Convert income statements to common-size income statements.

- A vertical common-size income statement expresses each item as a percentage of revenue. The common-size format standardizes the income statement by eliminating the effects of size. Common-size income statements are useful for trend analysis and for comparisons with peer firms.

### 21.j. Evaluate a company's financial performance using common-size income statements and financial ratios based on the income statements.

- Common-size income statements are useful in examining a firm's business strategies.
- Two popular profitability ratios are gross profit margin (gross profit / revenue) and net profit margin (net income / revenue). A firm can often achieve higher profit margins by differentiating its products from the competition.

### 21.k. Describe, calculate, and interpret comprehensive income.

- Comprehensive income is the sum of net income and other comprehensive income. it measures all changes to equity other than those from transactions with shareholders.

### 21.l. Describe other comprehensive income and identify major types of items included in it.

- Transactions with shareholders, such as dividends paid and shares issued for repurchased, are not reported on the income statement.
- Other comprehensive income includes other transactions that affect equity but do not affect net income, including:
    - Gains and losses from foreign currency translation.
    - Pension obligation adjustments.
    - Unrealized gains and losses from cash flow hedging derivatives.
    - Unrealized gains and losses on available-for-sale securities.

## Understanding Balance Sheets

### 22.a. Describe the elements of the balance sheet: assets, liabilities, and equity.

- Assets are resources controlled as result of past transactions that are expected to provide future economic benefits.
- Liabilities are obligations as a result of past events that are expected to require an outflow of economic resources.
- Equity is the owners' residual interest in the assets after deducting the liabilities.
- A financial statement item should be recognized if a future economic benefit to or from the firm is probable and the item's value or cost can be measured reliably.

### 22.b. Describe uses and limitations of the balance sheet in financial analysis.

- The balance sheet can be sued to assess a firm's liquidity, solvency, and ability to pay dividends to shareholders.
- Balance sheet assets, liabilities, and equity should not be interpreted as market value or intrinsic value. For most firms, the balance sheet consists of a mixture of values including historical cost, amortized cost, and fair value.
- Some assets and liabilities are difficult to quantify and are not reported on the balance sheet.

### 22.c. Describe alternative formats of balance sheet presentation.

- A classified balance sheet separately reports current and noncurrent assets and current and noncurrent liabilities.
- Alternatively, liquidity-based presentations, often used in the banking industry, present assets and liabilities in order of liquidity.

### 22.d. Distinguish between current and non-current assets and current and non-current liabilities.

- Current (noncurrent) assets are those expected to be used up or converted to cash in less than (more than) one year or the firm's operating cycle, whichever is greater.
- Current (noncurrent) liabilities are those the firm expects to satisfy in less than (more than) one year or the firm's operating cycle, whichever is greater.

### 22.e. Describe different types of assets and liabilities and the measurement bases of each.

- Cash equivalents are short-term, highly liquid financial assets that are readily convertible to cash. Their balance sheet values are generally close to identical using either amortized cost or fair value.
- Accounts receivable are reported at net realizable value by estimating bad debt expense.
- Inventories are reported at the lower of cost or net realizable value (IFRS) or the lower of cost or market (U.S. GAAP). Cost can be measured using standard costing or the retail method. Different cost flow assumptions can affect inventory values.
- Property, plant, and equipment (PP&E) can be reported using the cost model or the revaluation model under IFRS. Under U.S. GAAP, only the cost model is allowed. PP&E is impaired if its carrying value exceeds the recoverable amount. Recoveries of impairment losses are allowed under IFRS but not U.S. GAAP.
- Intangible assets create internally are expensed as incurred. Purchased intangibles are reported similar to PP&E. Under IFRS, research costs are expensed as incurred and development costs are capitalized. Both research and development costs are expensed under U.S. GAAP.
- Goodwill is the excess of purchases price over the fair value of the identifiable net assets (assets minus liabilities) acquired in a business acquisition. Goodwill is not amortized but must be tested for impairment at least annually.
- Under IFRS, debt securities acquired with intent hold them to maturity are measured at amortized cost. Debt securities acquired with the intend to collect interest payments but sell before maturity are measured at fair value through other comprehensive income. Debt securities acquired with the intent to sell them in the near term, as well as equity securities and derivatives, are measured at fair value through profit and loss.
- IFRS permits firms to elect, irrevocably at the time of purchase, to measure equity securities at fair value through other comprehensive income, or any security at fair value through profit and loss.
- Under U.S. GAAP, held-to-maturity securities are reported at amortized cost. Trading securities, available-for-sale securities, and derivatives are reported at fair value. For trading securities and derivatives, unrealized gains and losses are recognized in the income statement. Unrealized gains and losses for available-for-sale securities are reported in equity (other comprehensive income).
- Accounts payable are amounts owed to suppliers for goods or services purchased on credit. Accrued liabilities are expenses that have been recognized in the income statement but are not yet contractually due. Unearned revenue is cash collected in advance of providing goods and services.
- Financial liabilities not issued at face value, like bonds payable, are reported at amortized cost. Held-for-trading liabilities and derivative liabilities are reported at fair value.

### 22.f. Describe the components of shareholders' equity.

- Owners' equity includes:
    - Contributed capital-the amount paid in by common shareholders.
    - Preferred stock-capital stock that has certain rights and privileges not possessed by the common shareholders. Classified as debt if mandatorily redeemable.
    - Treasury stock-issued common stock that has been repurchased by the firm.
    - Retained earnings-the cumulative undistributed earnings of the firm since inception.
    - Noncontrolling (minority) interest-the portion of a subsidiary that is not owned by the parent.
    - Accumulated other comprehensive income-includes all changes to equity from sources other than net income and transactions with shareholders.
- The statement of changes in stockholders' equity summarizes the transactions during a period that increase or decrease equity, including transactions with shareholders.

### 22.g. Convert balance sheets to common-size balance sheets and interpret common-size balance sheets.

- A vertical common-size balance sheet expresses each item of the balance sheet as a percentage of total assets. The common-size format standardizes the balance sheet by eliminating the effect of size. This allows for comparison over time (time-series analysis) and across firms (cross-sectional analysis).

### 22.h. Calculate and interpret liquidity and solvency ratios.

- Balance sheet ratios, along with common-size analysis, can be sued to evaluate a firm's liquidity and solvency.
- Liquidity ratios measure the firm's ability to satisfy its short-term obligations as they come due. Liquidity ratios include the current ratio, the quick ratio, and the cash ratio.
- Solvency ratios measure the firm's ability to satisfy its long-term obligations. Solvency ratios include the long-term debt-to-equity ratio, the total debt-to-equity ratio, the debt- ratio, and the financial leverage ratio.

## Understanding Cash Flow Statements

### 23.a. Compare cash flows from operating, investing, and financing activities and classify cash flow items as relating to one of those three categories given a description of the items.

- Cash flow from operating activities (CFO) consists of the inflows and outflows of cash resulting from transactions that affect a firm's net income.
- Cash flow from investing activities (CFI) consists of the inflows and outflows of cash resulting from the acquisition or disposal of long-term assets and certain investments.
- Cash flow from financing activities (CFF) consists of the inflows and outflows of cash resulting from transactions affecting a firm's capital structure, such as issuing or repaying debt and issuing or repurchasing stock.

### 23.b. Describe how non-cash investing and financing activities are reported.

- Noncash investing and financing activities, such as taking on debt to the seller of a purchased asset, are not reported in the cash flow statement but must be disclosed in the footnotes or a supplemental schedule.

### 23.c. Contrast cash flow statements prepared under International Financial Reporting Standards (IFRS) and US generally accepted accounting principles (US GAAP).

- Under U.S. GAAP, dividends paid are financing cash flows. Interest paid, interest received, and dividends received are operating cash flows. all taxes paid are operating cash flows.
- Under IFRS, dividends paid and interest paid can be reported as either operating or financing cash flows. Interest received and dividends received can be reported as either operating or investing cash flows. Taxes paid are operating cash flows unless they arise from an investing or financing transaction.

### 23.d. Distinguish between the direct and indirect methods of presenting cash from operating activities and describe arguments in favor of each method.

- Under the direct method of presenting CFO, each line item of the accrual-based income statement is adjusted to get cash receipts or cash payments. The main advantage of the direct method is that it presents clearly the firm's operating cash receipts and payments.
- Under the indirect method of presenting CFO, net income is adjusted for transactions that affect net income but do not affect operating cash flow, such as depreciation and gains or losses on asset sales, and for changes in balance sheet items. The main advantage of the indirect method is that it focuses on the differences between net income and operating cash flow. This provides a useful link to the income statement when forecasting future operating cash flow.

### 23.e. Describe how the cash flow statement is linked to the income statement and the balance sheet.

- Operating activities typically relate to the firm's current assets and current liabilities.
- Investing activities typically relate to noncurrent assets.
- Financing activities typically relate to noncurrent liabilities and equity.
- Timing of revenue or expense recognition that differs from the receipt or payment of cash is reflected in changes in balance sheet accounts.

### 23.f. Describe the steps in the preparation of direct and indirect cash flow statements, including how cash flows can be computed using income statement and balance sheet data.

- The direct methods of calculating CFO is to sum cash inflows and cash outflows for operating activities.
    - Cash collections from customers-sales adjusted for changes in receivable and unearned revenue.
    - Cash paid for inputs-COGS adjusted for changes in inventory and accounts payable.
    - Cash operating expenses-SG&A adjusted for changes in related accrued liabilities or prepaid expenses.
    - Cash interest paid-interest expense adjusted for the change in interest payable.
    - Cash taxes paid-income tax expense adjusted for changes in taxes payable and changes in deferred tax assets and liabilities.

### 23.g. Convert cash flows from the indirect to direct method.

- An indirect cash flow statement can be converted to a direct cash flow statement by adjusting each income statement account for changes in associated balance sheet accounts and by eliminating noncash and non-operating items.

### 23.h. Analyze and interpret both reported and common-size cash flow statements.

- An analyst should determine whether a company is generating positive operating cash flow over time that is greater than its capital spending needs and whether the company's accounting policies are causing reported earnings to diverge from operating cash flow.
- A common-size cash flow statement shows each item as a percentage of revenue or shows each cash inflow as a percentage of total inflows and each outflow as a percentage of total outflows.

### 23.i. Calculate and interpret free cash flow to the firm, free cash flow to equity, and performance and coverage cash flow ratios.

- Free cash flow to the firm (FCFF) is the cash available to all investors, both equity owners and debt holders.
- FCFF = net income + noncash charges + [cash interest paid * (1 - tax rate)] - fixed capital investment - working capital investment
- FCFF = CFO + [cash interest paid * (1 - tax rate)] - fixed capital investment
- Free cash flow to equity (FCFE) is the cash flow that is available for distribution to the common shareholders after all obligations have been paid.
- FCFE = CFO - fixed capital investment + net borrowing
- Cash flow performance ratios, such as cash return on equity or on assets, and cash coverage ratios, such as debt coverage or cash interest coverage, provide information about the firm's operating performance and financial strength.

## Financial Analysis Techniques

### 24.a. Describe tools and techniques used in financial analysis, including their uses and limitations.

- Ratios can be used to project earnings and future cash flow, evaluate a firm's flexibility, assess management's performance, evaluate changes in the firm and industry over time, and compare the firm with industry competitors.
- Vertical common-size data are stated as a percentage of sales for income statements or as a percentage of total assets for balance sheets. Horizontal common-size data present each item as a percentage of tis value in a base year.
- Ratio analysis has limitations. Ratios are not useful when viewed in isolation and require adjustments when different companies use different accounting treatments. Comparable ratios may be hard to find for companies that operate in multiple industries. Ratios must be analyzed relative to one another, and determining the range of acceptable values for a ratio can be difficult.

### 24.b. Classify, calculate, and interpret activity, liquidity, solvency, profitability, and valuation ratios.

- Activity ratios indicate how well a firm uses its assets. They include receivables turnover, days of sales outstanding, inventory turnover, days of inventory on hand, payables turnover, payables payment period, and turnover ratios for total assets, fixed assets, and working capital.
- Liquidity ratios indicate a firm's ability to meet its short-term obligations. They include the current, quick, and cash ratios, the defensive interval, and the cash conversion cycle.
- Solvency ratios indicate a firm's ability to meet its long-term obligations. They include the debt-to-equity, debt-to-capital, debt-to-assets, financial leverage, interest coverage, and fixed charge coverage ratios.
- Profitability ratios indicate how well a firm generates operating income and net income. They include net, gross, and operating profit margins, pretax margin, return on assets, operating return on assets, return on total capital, return on total equity, and return on common equity.
- Valuation ratios are used to compare the relative values of stocks. They include earnings per share and price-to-earnings, price-to-sales, price-to-book value, and price-to-cash-flow ratios.

### 24.c. Describe relationships among ratios and evaluate a company using ratio analysis.

- An analyst should use an appropriate combination of different ratios to evaluate a company over time and relative to comparable companies. The interpretation of an increase in ROE, for example, may be quite different for a firm that has significantly increased its financial leverage compared to one that has maintained or decreased its financial leverage.

### 24.d. Demonstrate the application of DuPont analysis of return on equity and calculate and interpret effects of changes in its components.

- Basic DuPont Equation:
    - ROE = (net income / sales) * (sales / assets) * (assets / equity)
- Extended DuPont Equation:
    - ROE = (net income / EBT) * (EBT / EBIT) * (EBIT / revenue) * (revenue / total assets) * (total assets / total equity)

### 24.e. Calculate and interpret ratios used in equity analysis and credit analysis.

- Ratios used in equity analysis include price-to-earnings, price-to-cash flow, price-to-sales, and price-to-book value ratios, and basic and diluted earnings per share. Other ratios are relevant to specific industries such as retail and financial services.
- Credit analysis emphasize interest coverage ratios, return on capital, debt-to-assets ratios, and cash flow to total debt.

### 24.f. Explain the requirements for segment reporting and calculate and interpret segment ratios.

- A business or geographic segment is a portion of a firm that has risk and return characteristics distinguishable form the rest of the firm and accounts for more than 10% of the firm's sales or assets.
- Firms are required to report some items for significant business and geographic segments. Profitability, leverage, and turnover ratios by segment can give the analyst a better understanding of the performance of the overall business.

### 24.g. Describe how ratio analysis and other techniques can be used to model and forecast earnings.

- Ratio analysis in conjunction with other techniques can be used to construct pro forma financial statements based on a forecast of sales growth and assumptions about the relation of changes in key income statement and balance sheet items to growth of sales.

## Inventories

### 25.a. Distinguish between costs included in inventories and costs recognized as expenses in the period in which they are incurred.

- Costs included in inventory on the balance sheet include purchase cost, conversion costs, and other costs necessary to bring the inventory to its present location and condition. All of these costs for inventory acquired or produced in the current period are added to beginning inventory value and then allocated either to cost of goods sold for the period or to ending  inventory.
- Period costs, such as abnormal waste, most storage costs, administrative costs, and selling costs, are expensed as incurred.

### 25.b. Describe different inventory valuation methods (cost formulas).

- Inventory cost flow methods:
    - FIFO: The cost of the first item purchased is the cost of the first item sold. Ending inventory is based on the cost of the most recent purchases, thereby approximating current cost.
    - LIFO: The cost of the last item purchased is the cost of the first item sold. Ending inventory is based on the cost of the earliest items purchased. LIFO is prohibited under IFRS.
    - Weighted average cost: COGS and inventory values are between their FIFO and FIFO values.
    - Specific identification: Each unit sold is matched with the unit's actual cost.

### 25.c. Calculate and compare cost of sales, gross profit, and ending inventory using different inventory valuation methods and using perpetual and periodic inventory systems.

- Under LIFO, cost of sales reflects the most recent purchases or production costs, and balance sheet inventory values reflect older outdated costs.
- Under FIFO, cost of sales reflects the oldest purchase or production costs for inventory, and balance sheet inventory values reflect the most recent costs.
- Under the weighted average cost method, cost of sales and balance sheet inventory values are between those of LIFO and FIFO.
- When purchase or production costs are rising, LIFO cost of sales is lower than FIFO cost of sales, and LIFO gross profit is lower than FIFO gross profit as a result. LIFO inventory is lower than FIFO inventory.
- When purchase or production costs are falling, LIFO cost of sales is lower than FIFO cost of sales, and LIFO gross profit is higher than FIFO gross profit as a result. LIFO inventory is higher than FIFO inventory.
- In either case, LIFO cost of sales and FIFO inventory values better represent economic reality (replacement costs).
- In a periodic system, inventory values and COGS are determined at the end of the accounting period. In a perpetual system, inventory values and COGS are updated continuously.
- In the case of FIFO and specific identification, ending inventory values and COGS are the same whether a periodic or perpetual system is used. LIFO and weighted average cost, however, can produce different inventory values and COGS depending on whether a periodic or perpetual system is used.

### 25.d. Calculate and explain how inflation and deflation of inventory costs affect the financial statements and ratios of companies that use different inventory valuation methods.

- When prices are increasing and inventory quantities are stable or increasing:
    - LIFO results in
        - higher COGS
        - lower gross profit
        - lower inventory balances
        - higher inventory turnover
    - FIFO results in
        - lower COGS
        - higher gross profit
        - higher inventory balances
        - lower inventory turnover
- When prices are decreasing and inventory quantities are stable or increasing:
    - LIFO results in
        - lower COGS
        - higher gross profit
        - higher inventory balances
        - lower inventory turnover
    - FIFO results in
        - higher COGS
        - lower gross profit
        - lower inventory balances
        - higher inventory turnover
- The weighted average cost method results in values between those of LIFO and FIFO if prices are increasing or decreasing.

### 25.e. Explain LIFO reserve and LIFO liquidation and their effects on financial statements and ratios.

- A firm that reports under LIFO must disclose a LIFO reserve, which is the difference between LIFO inventory reported and inventory has the firm used the FIFO method. LIFO reserve will be positive during periods of rising inventory costs and negative during periods of falling inventory costs.
- A LIFO liquidation occurs when a firm using LIFO sells more inventory during a period than it produces. During periods of rising prices, this drawdown in inventory reduces cost of goods sold because the lower cost of previously produced inventory is used, resulting in an unsustainable increase in gross profit margin.

### 25.f. Convert a company's reported financial statements from LIFO to FIFO for purposes of comparison.

- To convert a firm's financial statements from LIFO to what they would have been under FIFO:
    1. Add the LIFO reserve to LIFO inventory
    2. Subtract the change in the LIFO reserve for the period from COGS
    3. Decrease cash by LIFO reserve * tax rate
    4. Increase retained earnings (equity) by LIFO reserve * (1 - tax rate)

### 25.g. Describe the measurement of inventory at the lower of cost and net realizable value.

- Under IFRS, inventories are valued at the lower of cost or net realizable value. Inventory write-ups are allowed, but only to the extent that a previous write-down to net realizable value was recorded.
- Under U.S. GAAP, inventories are valued at the lower of cost or net realizable value for companies using cost methods other than LIFO or the retail method. For companies using LIFO or the retail method, inventories are valued at the lower of cost or market. Market is usually equal to replacement cost but cannot exceed net realizable value or be less than net realizable value minus a normal profit margin. No subsequent write-up is allowed for any company reporting under U.S. GAAP.

### 25.h. Describe implications of valuing inventory at net realizable value for financial statements and ratios.

- A write-down of inventory value form cost to net realizable value will:
    - Decrease inventory, assets, and equity
    - Increase asset turnover, the debt to equity ratio and the debt to assets ratio
    - Result in a loss on the income statement, which will decrease net income and the net profit margin, as well as ROA and ROE for a typical firm.

### 25.i. Describe the financial statement presentation of and disclosures relating to inventories.

- Required inventory disclosures:
    - The cost flow method (LIFO, FIFO, etc.) used
    - Total carrying value of inventory and carrying value by classification (raw materials, work-in-process, and finished goos) if appropriate
    - Carrying value of inventories reported at fair value less selling costs
    - The cost of inventory recognized as an expense (COGS) during the period
    - Reversals of inventory write-downs during the period (IFRS only because U.S. GAAP does not allow reversals)
    - Carrying value of inventories pledged as collateral

### 25.j. Explain issues that analysts should consider when examining a company's inventory disclosures and other sources of information.

- An analyst should examine inventory disclosures to determine whether:
    - The finished goods category is growing while raw materials and goods in process are declining, which may indicate decreasing demand and potential future inventory write-downs.
    - Raw materials and goods in process are increasing, which may indicate increasing future demand and higher earnings.
    - Increases in finished goods are greater than increases in sales, which may indicate decreasing demand or inventory obsolescence and potential future inventory write-downs.

### 25.k. Calculate and compare ratios of companies, including companies that use different inventory methods.

- Inventory turnover, days of inventory on hand, and gross profit margin can be used to evaluate the quality of a firm's inventory management.
- Inventory turnover that is too slow (high days of inventory on hand) may be an indication of slow-moving or obsolete inventory.
- High inventory turnover together with low sales growth relative to the industry may indicate inadequate inventory levels and lost sales because customer orders could not be fulfilled.
- High inventory turnover together with high sales growth relative to the industry average suggests that high inventory turnover reflects greater efficiency rather than inadequate inventory.

### 25.l. Analyze and compare the financial statements of companies, including companies that use different inventory methods.

- Comparison of company financial statements may require statements to be adjusted to reflect the same inventory costing methods for both firms, or for the subject firm and any industry or peer group of firms used for comparison.

## Long-Lived Assets

### 26.a. Distinguish between costs that are capitalized and costs that are expensed in the period in which they are incurred.

- When an asset is expected to provide benefits for only the current period, its cost is expensed on the income statement for the period. If an asset is expected to provide benefits over multiple periods, it is capitalized rather than expensed.

### 26.b. Compare the financial reporting of the following types of intangible assets: purchased, internally developed, acquired in a business combination.

- The cost of a purchased finite-lived intangible asset is amortized over its useful life. Indefinite-lived intangible assets are not amortized, but are tested for impairment at least annually. The cost of internally developed intangible assets is expensed.
- Under IFRS, research costs are expensed but development costs may be capitalized. Under U.S. GAAP, both research and development costs are expensed as incurred, except in the case of software created for sale to others.
- The acquisition method is used to account for assets acquired in a business combination. The purchase price is allocated to the fair value of identifiable assets of the acquired firm less its liabilities. Any excess of the purchase price above the fair value of the acquired firm's net assets is recorded as goodwill, an unidentifiable intangible asset that cannot be separated from the business itself.

### 26.c. Explain and evaluate how capitalizing versus expensing costs in the period in which they are incurred affects financial statements and ratios.

- With capitalization, the asset value is put on the balance sheet and the cost is expensed through the income statement over the asset's useful life through either depreciation or amortization. Compared to expensing the asset cost, capitalization results in:
    - Lower expense and higher net income in period of acquisition, higher expense (deprecation or amortization) and lower net income in each of the remaining years of the asset's life.
    - Higher assets and equity
    - Lower CFI and higher CFO because the cost of capitalized asset is classified as an investing cash outflow.
    - Higher ROE and ROA in the initial period, and lower ROE and ROA in subsequent periods because net income is lower and both assets and equity are higher.
    - Lower debt-to-assets and debt-to-equity ratios because assets and equity are higher.

### 26.d. Describe the different depreciation methods for property, plant, and equipment and calculate depreciation expense.

- Depreciation methods:
    - Straight-line: Equal amount of expense each period
        - Depreciation expense = (original cost - salvage value) / depreciable life
    - Accelerated (declining balance): Higher depreciation expense in the early years and lower deprecation expense in the later years of an asset's life
        - Double-declining balance (DDB), an accelerated depreciation method:
            - DDB depreciation in year x = 2 / depreciation life in years * book value at beginning of year x
    - Units-of-production: Expense based on percentage usage rather than time
        - (original cost - salvage value) / life in output units * output units used in the period
- IFRS requires component depreciation, in which significant parts of an asset are identified and depreciated separately.

### 26.e. Describe how the choice of depreciation method and assumptions concerning useful life and residual value affect depreciation expense, financial statements, and ratios.

- In the early years of an asset's life, accelerated depreciation results in higher depreciation expense, lower net income, and lower ROA and ROE compared to straight-line depreciation. Cash flow is the same assuming tax depreciation is unaffected by the choice of method for financing reporting.
- Firms can reduce depreciation expense and increase net income by using longer useful life and higher salvage values.

### 26.f. Describe the different amortization methods for intangible assets with finite lives and calculate amortization expense.

- Amortization methods for intangible assets with finite lives are the same as those for depreciation: straight line, accelerated, or units of production. Calculation of amortization expense for such assets is the same as with depreciation expense.

### 26.g. Describe how the choice of amortization method and assumptions concerning useful life and residual value affect amortization expense, financial statements, and ratios.

- The choice of amortization method will affect expenses, assets, equity, and financial ratios in exactly the same way that the choice of depreciation method will. Just as with the depreciation of tangible assets, increasing either the estimate of an asset's useful life or the estimate of its residual value will reduce annual amortization expense, which will increase net income, assets, ROE, and ROA for a typical firm.

### 26.h. Describe the revaluation model.

- Under IFRS, firms have the option to revalue assets based on fair value under the revaluation model. U.S. GAAP does not permit revaluation.
- The impact of revaluation on the income statement depends on whether the initial revaluation resulted in a gain or loss. If the initial revaluation resulted in a loss (decrease in carrying value), the initial loss would be recognized in the income statement and any subsequent gain would be recognized in the income statement only to the extent of the previously reported loss. Revaluation gains beyond the initial loss bypass the income statement and are recognized in shareholders' equity as a revaluation surplus.
- If the initial revaluation resulted in a gain (increase in carrying value), the initial gain would bypass the income statement and be reported as a revaluation surplus. Later revaluation losses would first reduce the revaluation surplus.

### 26.i. Explain the impairment of property, plant, and equipment and intangible assets.

- Under IFRS, an asset is impaired when its carrying value exceeds the recoverable amount. The recoverable amount is the greater of fair value less selling costs and the value in use (present value of expected cash flows). If impaired, the asset is written down to the recoverable amount. Loss recoveries are permitted, but not above.
- Under U.S. GAAP, an asset is impaired if its carrying value is greater than the asset's undiscounted future cash flows. If impaired, the asset is written down to fair value. Subsequent recoveries are not allowed for assets held for use.
- Asset impairments result in losses in the income statement. Impairments have no impact on cash flow as they have no tax or other ash flow effects until disposal of the asset.

### 26.j. Explain the derecognition of property, plant, and equipment and intangible assets.

- When a long-lived asset is sold, the difference between the sale proceeds and the carrying (book) value of the asset is reported as a gain or loss in the income statement.
- When a long-lived asset is abandoned, the carrying value is removed from the balance sheet and a loss if recognized in that amount.
- If a long-lived asset is exchanged for another asset, a gain or loss is computed by comparing the carrying value of the old asset with fair value of the old asset (or fair value of the new asset if more clearly evident).

### 26.k. Explain and evaluate how impairment, revaluation, and derecognition of property, plant, and equipment and intangible assets affect financial statements and ratios.

- Impairment charges decrease net income, assets, and equity, which results in lower ROA and ROE and higher debt-to-equity and debt-to-assets ratios for a typical firm.
- Upward revaluation increases assets and equity, and thereby decreases debt-to-assets and debt-to-equity ratios. A downward revaluation has opposite effects. The effect on net income and related ratios depends on whether the revaluation is to a value above or below cost.
- Derecognition of assets can result in either a gain or loss on the income statement. A loss will reduce net income and assets, while a gain will increase net income and assets.

### 26.l. Describe the financial statement presentation of and disclosures relating to property, plant, and equipment and intangible assets.

- There are many differences in the disclosure requirements for tangible and intangible assets under IFRS and U.S. GAAP. However, firms are generally required to disclose:
    - Carrying values for each class of asset.
    - Accumulated depreciation and amortization.
    - Title restrictions and assets pledged as collateral.
    - For impaired assets, the loss amount and the circumstances that caused the loss.
    - For revalued assets (IFRS only), the revaluation date, how fair value was determined, and the carrying value using the historical cost model.

### 26.m. Analyze and interpret financial statement disclosures regarding property, plant, and equipment and intangible assets.

- Analysts can use disclosures of the historical cost, accumulated depreciation (amortization), and annual depreciation (amortization) expenses to estimate average age of assets, total useful life of assets, and remaining useful life of assets. These estimates are more accurate for firms that use straight-line depreciation.
- average age = accumulated depreciation / annual depreciation expenses
- total useful life = historical cost / annual depreciation expenses
- remaining useful life = ending net PP&E / annual depreciation expenses

### 26.n. Compare the financial reporting of investment property with that of property, plant, and equipment.

- Under IFRS (but not U.S. GAAP), investment property is defined as property owned for the purpose of earning rent, capital appreciation, or both. Firms can account for investment property using the cost model or the fair value model. Unlike the revaluation model for property, plant, and equipment, increases in the fair value of investment property above its historical cost are recognized as gains on the income statement if the firm uses the fair value model.

## Income Taxes

### 27.a. Describe the differences between accounting profit and taxable income and define key terms, including deferred tax assets, deferred tax liabilities, valuation allowance, taxes payable, and income tax expense.

- Deferred tax terminology:
    - Taxable income - Income subject to tax based on the tax return.
    - Accounting profit - Pretax income from the income statement based on financial accounting standards.
    - Deferred tax assets - Balance sheet asset value that results when taxes payable (tax return) are greater than income tax expense (income statement) and the different is expected to reverse in future periods.
    - Deferred tax liabilities - Balance sheet liability value that results when income tax expenses (income statement) is greater than taxes payable (tax return) and the difference is expected to reverse in future periods.
    - Valuation allowance - Reduction of deferred tax assets (contra account) based on the likelihood that the future tax benefit will not be realized.
    - Taxes payable - The tax liability from the tax return. Note that his term also refers to a liability that appears on the balance sheet for taxes due but not yet paid.
    - Income tax payable - Expense recognized in the income statement that includes taxes payable and changes in deferred tax assets and liabilities.

### 27.b. Explain how deferred tax liabilities and assets are created and the factors that determine how a company's deferred tax liabilities and assets should be treated for the purposes of financial analysis.

- A deferred tax liability is created when income tax expense (income statement) is higher than taxes payable (tax return). Deferred tax liabilities occur when revenues (or gains) are recognized in the income statement before they are taxable on the tax return, or expenses (or losses) are tax deductible before they are recognized in the income statement.
- A deferred tax asset is created when taxes payable (tax return) are higher than income tax expense (income statement). Deferred tax assets are recorded when revenues (or gains) are taxable before they are recognized in the income statement, when expenses (or losses) are recognized in the income statement before they are tax deductible, or when tax loss carryforwards are available to reduce future taxable income.
- Deferred tax liabilities that are not expected to reverse, typically because of expected continued growth in capital expenditures, should be treated for analytical purposes as equity. If deferred tax liabilities are expected to reverse, they should be treated for analytical purposes as liabilities.

### 27.c. Calculate the tax base of a company's assets and liabilities.

- An asset's tax base is its value for tax purposes. The tax base for a depreciable fixed asset is its cost minus any depreciation or amortization previously taken on the tax return. When an asset is sold, the taxable gain or loss on the sale is equal to the sale price minus the asset's tax base.
- A liability's tax base is its value for tax purposes. When there is a difference between the book value of a liability on a firm's financial statements and its tax base that will result in future taxable gains or losses when the liability is settled, the firm will recognize a deferred tax asset or liability to reflect this future tax or tax benefit.

### 27.d. Calculate income tax expense, income taxes payable, deferred tax assets, and deferred tax liabilities, and calculate and interpret the adjustment to the financial statements related to a change in the income tax rate.

- If taxable income is less than pretax income and the cause of the difference is expected to reverse in future years, a DTL is created. If taxable income is greater than pretax income and the difference is expected to reverse in future years, a DTA is created.
- The balance of the DTA or DTL is equal to the difference between the tax base and the carrying value of the asset or liability, multiplied by the tax rate.
- Income tax expense and taxes payable are related through the change in the dTA and the change in the DTL:
    - income tax expense = taxes payable + (ending DTL - beginning DTL) - (ending DTA - beginning DTA)

### 27.e. Evaluate the effect of tax rate changes on a company's financial statements and ratios.

- When a firm's income tax rate increases (decreases), deferred tax assets and deferred tax liabilities are both increased (decreased) to reflect the new rate. Changes in these values will also affect income tax expense.
- An increase in the tax rate will increase both a firm's DTL and its income tax expense. A decrease in the tax rate will decrease both a firm's DTL and its income tax expense.
- An increase in the tax rate will increase a firm's DTA and decrease its income tax expense. A decrease in the tax rate will decrease a firm's DTA and increase its income tax expense.

### 27.f. Distinguish between temporary and permanent differences in pre-tax accounting income and taxable income.

- A temporary difference is a difference between the tax base and the carrying value of an asset or liability that will result in taxable amounts or deductible amounts in the future.
- A permanent difference is a difference between taxable income and pretax income that will not reverse in the future. Permanent differences do not create DTAs or DTLs.

### 27.g. Describe the valuation allowance for deferred tax assets-when it is required and what effect it has on financial statements.

- If it is more likely than not that some or all of a DTA will not be realized (because of insufficient future taxable income to recover the tax asset), then the DTA must be reduced by a valuation allowance. The valuation allowance is a contra account that reduces the DTA value on the balance sheet. Increasing the valuation allowance will increase income tax expense and reduce earnings. If circumstances change, the DTA can be revalued upward by decreasing the valuation allowance, which would increase earnings.

### 27.h. Explain recognition and measurement of current and deferred tax items.

- Measurement of deferred tax items depends on the tax rate expected to be in force when the underlying temporary difference reverses. The applicable tax may depend on how the temporary difference will be settled (e.g., if a capital gains tax rate will apply). If a change that leads to a deferred tax item is taken directly to equity, such as an upward revaluation, the deferred tax item should also be taken directly to equity.

### 27.i. Analyze disclosures relating to deferred tax items and the effective tax rate reconciliation and explain how information included in these disclosures affects a company's financial statements and financial ratios.

- Firms are required to reconcile their effective income tax rate with the applicable statutory rate in the country where the business is domiciled. Analyzing trends in individual reconciliation items can aid in understanding past earnings trends and in predicting future effective tax rates. Where adequate data is provided, they can also be helpful in predicting future earnings and cash flows or for adjusting financial ratios.

### 27.j. Identify the key provisions of and differences between income tax accounting under International Financial Reporting Standards (IFRS) and US generally accepted accounting principles (GAAP).

- The accounting treatment of income taxes under U.S. GAAP and their treatment under IFRS are similar in most respects. One major difference relates to the revaluation of fixed assets and intangible assets. U.S. GAAP prohibits upward revaluations, but they are permitted under IFRS and any resulting effects on deferred tax are recognized in equity.

## Non-Current (Long-Term) Liabilities

### 28.a. Determine the initial recognition, initial measurement and subsequent measurement of bonds.

- When a bond is issued, assets and liabilities both initially increase by the bond proceeds. At any point in time, the book value of the bond liability is equal to the present value of the remaining future cash flows (coupon payments and maturity value) discounted at the market rate of interest at issuance. The proceeds are reported in the cash flow statement as an inflow from financing activities.
- A premium bond (coupon rate > market yield at issuance) is reported on the balance sheet at a value greater than its face value. As the premium is amortized (reduced), the book value of the bond liability will decrease until it reaches its face value at maturity.
- A discount bond (market yield at issuance > coupon rate) is reported on the balance sheet at less than its face value. As the discount is amortized, the book value of the bond liability will increase until it reaches its face value at maturity.

### 28.b. Describe the effective interest method and calculate interest expense, amortization of bond discounts / premiums, and interest payments.

- Interest expense includes amortization of any discount or premium at issuance. Using the effective interest rate method, interest expense is equal to the book value of the bond liability at the beginning of the period multiplied by the bond's yield at issuance.
- For a premium bond, interest expense is less than the coupon payment (yield < coupon rate). The difference between interest expense and the coupon payment is subtracted from the bond liability on the balance sheet.
- For a discount bond, interest expense is greater than the coupon payment (yield > coupon rate). The difference between interest expense and the coupon payment is added to the bond liability on the balance sheet.

### 28.c. Explain the derecognition of debt.

- When bonds are redeemed before maturity, a gain or loss is recognized equal to the difference between the redemption price and the carrying (book) value of the bond liability at the reacquisition date.

### 28.d. Describe the role of debt covenants in protecting creditors.

- Debt covenants are restrictions on the borrower that protect the bondholders' interests, thereby reducing both default risk and borrowing costs. Covenants can include restrictions on dividend payments and share repurchases; mergers and acquisitions; sale, leaseback, and disposal of certain assets; and issuance of new debt in the future. Other covenants require the firm to maintain ratios or financial statement items at specific level.

### 28.e. Describe the financial statement presentation of and disclosures relating to debt.

- The firm separately discloses details about its long-term debt in the footnotes. These disclosures are useful for determining the timing and amount of future cash outflows. The disclosures usually include a discussion of the nature of the liabilities, maturity dates, stated and effective interest rates, call provisions and conversion privileges, restrictions imposed by creditors, assets pledged as security, and the amount of debt maturing in each of the next five years.

### 28.f. Explain motivations for leasing assets instead of purchasing them.

- Advantages of leasing rather than purchasing an asset may include lower-cost financing, fewer restrictions, and less risk of obsolescence.

### 28.g. Explain the financial reporting of leases from a lessee's perspective.

- Under IFRS, except for short-term leases, a lessee reports an asset and a liability on its balance sheet, both equal to the present value of the promised lease payments. The interest portion of each lease payment is reported as interest expense, while the principal-repayment portion of each payment reduces the lease liability. For short-term leases, rent expense is reported on the income statement and no balance sheet entries are required.
- Under U.S. GAAP, a lease is classified as a finance lease if the benefits and risks of ownership have been substantially transferred to the lessee, or as an operating lease otherwise. Reporting for a finance lease is the same as under IFRS. For an operating lease, the entire lease payment is recorded as a lease expense while the principal portion reduces the lease liability.

### 28.h. Explain the financial reporting of leases from a lessor's perspective.

- Under IFRS, there are two lease classifications for lessors, finance leases and operating leases. With a finance lease, the lessor removes the leased asset from its balance sheet and adds a lease receivable asset. The lessor reports the interest portion of the lease payments as income. for an operating lease, the lessor reports lease payments as income and depreciation and other costs are expenses.
- Under U.S. GAAP, lessor classification for leases are sales-type, direct financing, or operating. A lease is sales-type if it meets the transfer of ownership criteria and collection of the lease payments is probable. A lease is direct financing if the transfer of ownership criteria are not net, a third party guarantees the residual value,  and the lease payments plus the residual value at lease equal the fair value of the asset. A lease that is neither sales-type nor direct financing is an operating lease.

### 28.i. Compare the presentation and disclosure of defined contribution and defined benefit pension plans.

- A firm reports a net pension liability on its balance sheet if the fair value of a defined benefit plan's assets is less than the estimated pension obligation, or a net pension asset if the fair value of the plan's assets is greater than the estimated pension obligation. The change in the net pension asset or liability is reflected in a firm's comprehensive income each year.
- Pension expense for a defined contribution pension plan is equal to the employer's contributions.

### 28.j. Calculate and interpret leverage and coverage ratios.

- Analysts use solvency ratios to measure a firm's ability to satisfy its long-term obligations. In evaluating solvency, analysts look at leverage ratios and coverage ratios.
- Leverage ratios, such as debt-to-assets, debt-to-capital, debt-to-equity, and the financial leverage ratio, focus on the balance sheet.
    - Debt-to-assets ratio = total debt / total assets
    - Debt-to-capital ratio = total debt / (total debt + total equity)
    - Debt-to-equity ratio = total debt / total equity
    - Financial leverage ratio = average total assets / average total equity
- Coverage ratios, such as interest coverage and fixed charge coverage, focus on the income statement.
    - Interest coverage = EBIT / interest payments
    - Fixed charge coverage = (EBIT + lease payments) / (interest payments + lease payments)

## Financial Reporting Quality

### 29.a. Distinguish between financial reporting quality and quality of reported results (including quality of earnings, cash flow, and balance sheet items).

- Financial reporting quality refers to the characteristics of a firm's financial statements. High-quality financial reporting adheres to generally accepted accounting principles (GAAP) and is decision useful in terms of relevance and faithful representation.
- Quality of reported results refers to the level and sustainability of a firm's earnings, cash flows, and balance sheet items. High-quality earnings are high enough to provide the firm's investors with an adequate return and are sustainable in future periods.

### 29.b. Describe a spectrum for assessing financial reporting quality.

- A spectrum for assessing financial reporting quality consider both the quality of a firm's financial statements and the quality of its earnings. One such spectrum, form highest quality to lowest, is the following:
    - Reporting is compliant with GAAP and decision useful; earnings are sustainable and adequate.
    - Reporting is compliant and decision useful, but earnings quality is low.
    - Reporting is compliant, but earnings quality is low and reporting choices and estimates are biased.
    - Reporting is compliant, but earnings are actively managed.
    - Reporting is not compliant, but the numbers presented are based on the company's actual economic activities.
    - Reporting is not compliant and includes numbers that are fictitious or fraudulent.

### 29.c. Distinguish between conservative and aggressive accounting.

- Biased accounting choices that can be made within GAAP include conservative and aggressive accounting. Conservative accounting choices tend to decrease the company's reported earnings and financial position for the current period. Aggressive accounting choices tend to increase reported earnings or improve the financial position for the current period.
- Some managers employ conservative bias during periods when earnings are above target and aggressive bias during poor periods of below-target earnings to artificially smooth earnings.

### 29.d. Describe motivations that might cause management to issue financial reports that are not high quality.

- Motivations for firm managers to issue low-quality financial reports may include pressure to meet or exceed earnings targets, career considerations, increasing their compensation, improving perceptions of the firm among customers and suppliers, or meeting the terms of debt covenants.

### 29.e. describe conditions that are conductive to issuing low-quality, or even fraudulent, financial reports.

- Conditions that are often present when managers issue low-quality financial reports include motivations, opportunities, and rationalizations. Weak internal controls, inadequate oversight by the board of directors, and wide ranges of acceptable accounting treatments are among the factors that may provide opportunities for low-quality reporting.

### 29.f. Describe mechanisms that discipline financial reporting quality and the potential limitations of those mechanisms.

- Mechanisms that help to discipline financial reporting quality include regulation, auditing, and private contracts. Regulators typically require public companies to provide periodic financial statements and notes, including management commentary, and obtain independent audits.
- A clean audit opinion offers reasonable assurance that financial statements are free from material errors but does not guarantee the absence of error or fraud. The fact that firms select and pay their auditors may limit the effectiveness of auditing to discipline financial reporting quality.

### 29.g. Describe presentation choices, including non-GAAP measures, that could be used to influence an analyst's opinion.

- Firms may attempt to influence analysts' valuations by presenting non-GAAP measures, such as earnings that exclude certain nonrecurring items. IFRS requires firms to define and explain the relevance of any non-GAAP measures and reconcile them to the most comparable IFRS measure. Similar requirements apply to U.S. public firms.

### 29.h. Describe accounting methods (choices and estimates) that could be used to manage earnings, cash flow, and balance sheet items.

- Accounting choices and estimates that can be used to manage earnings include:
    - Revenue recognition choices such as shipping terms (FOB shipping point versus FOB destination), accelerating shipments (channel stuffing), and bill-and-hold transactions.
    - Estimates of reserves for uncollectible accounts or warranty expenses.
    - Valuation allowances on deferred tax assets.
    - Depreciation methods, estimates of useful lives and salvage values, and recognition of impairments.
    - Inventory cost flow methods.
    - Capitalization of expenses.
    - Related-party transactions.

### 29.i. Describe accounting warning signs and methods for detecting manipulation of information in financial reports.

- Accounting warning signs that indicate a need for closer analysis may include:
    - Revenue growth out of line with comparable firms, changes in revenue recognition methods, or lack of transparency about revenue recognition.
    - Decreases over time in turnover ratios (receivables, inventory, total asset).
    - Bill-and-hold, barter, or related-party transactions.
    - Net income not supported by operating cash flows.
    - Capitalization decisions, depreciation methods, useful lives, salvage values out of line with comparable firms.
    - Fourth-quarter earnings patterns not caused by seasonality.
    - Frequent appearance of nonrecurring items.
    - Emphasis on non-GAAP measures, minimal information and disclosure in financial reports.

## Applications of Financial Statement Analysis

### 30.a. Evaluate a company's past financial performance and explain how a company's strategy is reflected in past financial performance.

- Trends in a company's financial ratios and differences between its financial ratios and those of tis competitors or industry average ratios can reveal important aspects of its business strategy.

### 30.b. Forecast a company's future net income and cash flow.

- A company's future income and cash flows can be projected by forecasting sales growth and using estimates of profit margins and the increases in working capital and fixed assets necessary to support the forecast sales growth.

### 30.c. Describe the role of financial statement analysis in assessing the credit quality of a potential debt investment.

- Credit analysis uses a firm's financial statements to assess its credit quality. Indicators of a firm's creditworthiness include its scale and diversification, operational efficiency, margin stability, and use of financial leverage.

### 30.d. Describe the use of financial statement analysis in screening for potential equity investments.

- Potentially attractive equity investments can be identified by screening a universe of stocks, using minimum or maximum values of one or more ratios. Which (and how many) ratios to use, what minimum or maximum values to use, and how much importance to give each ratio all present challenges to the analyst.

### 30.e. Explain appropriate analyst adjustments to a company's financial statements to facilitate comparison with another company.

- When companies use different accounting methods or estimates relating to areas such as inventory accounting, depreciation, capitalization, and off-balance-sheet financing, analyst must adjust the financial statements for comparability.
- LIFO ending inventory can be adjusted to a FIFO basis by adding the LIFO reserve. LIFO cost of goods sold can be adjusted to a FIFO basis by subtracting the change in the LIFO reserve.
- When calculating solvency ratios, analysts should estimate the present value of operating lease obligations and add it to the firm's liabilities.