---
title: "WHAT I LEARNED LOSING A MILLION DOLLARS"
author: "Siyun Min"
date: "2022-06-20"
categories: [Book, Investment]
---
# <WHAT I LEARNED LOSING A MILLION DOLLARS>

[https://codahosted.io/docs/9TUJi-0GD4/blobs/bl-LS3XDD_Ubm/967682fc250afa9ea81cfe1b23a0c476b3ea50c4340eb78e6ba571b53e35b31ca35853a4e8a9c90caf1b634cb180345a11cde5d00c96228936552f077b34312cc9cc6ef05cc95620dd9a1e74da1e711bfdd9052e5a9ca424a00db761565d0cd8f358a7ff](https://codahosted.io/docs/9TUJi-0GD4/blobs/bl-LS3XDD_Ubm/967682fc250afa9ea81cfe1b23a0c476b3ea50c4340eb78e6ba571b53e35b31ca35853a4e8a9c90caf1b634cb180345a11cde5d00c96228936552f077b34312cc9cc6ef05cc95620dd9a1e74da1e711bfdd9052e5a9ca424a00db761565d0cd8f358a7ff)

> We hope the future will turn out well, but we fear it won’t. As members of the crowd we will always take these emotions to extremes. When the herd instinct combines with hope and fear in a market environment, we get panics and manias.
> 

> If you occasionally break the rules and still have an unbroken string of successes, you are likely to compound the problem because you assume that you are better than other people and above the rules. Your ego inflates, and you refuse to recognize the reality of a loss when it comes. You assume that you will be right. You assume that even if the market is against you, it will come back. Well, if I had an ego problem at one million dollars, what kind of problem would I have had if I had ridden through the valley of death and cheated death? If I had survived the loss and the market had gone on to make money for me, my ego problem would have been much worse.
> 

> When dealing with the risk of the uncertainty of the future, you have three choices: engineering, gambling, or speculating.
> 

> The engineer knows everything he needs to know for a technologically satisfactory answer to his problems. He builds safety margins into his calculations to eliminate any fringes of uncertainty.
> 

> The gambler, on the other hand, knows nothing about the event on which the outcome of his gambling depends because the distinguishing feature of gambling is that it deals with the unknown. The gambler plays for the excitement—the adrenaline rush. He isn’t playing to win—he is just playing.
> 

> The speculator doesn’t have the advantage of the engineer. The rules of natural science will not render the future direction of prices predictable. But the speculator does know more than the gambler because while the gambler is dealing with pure chance, the speculator has at least some knowledge about what determines the outcome of his activity. Speculating is the application of intellectual examination and systematic analysis to the problem of the uncertain future.
> 

> Successful investing is the result of successful speculation.
> 

> Federal Reserve Chairman Alan Greenspan put it this way: “The historic purpose of banking is to take prudent risks through the extension of loans to risk taking businesses.”5 In other words, the bankers are speculating.
> 

시장에 참여하는 것은(포지션을 갖는 것은) 모두 의사결정이다. 성공적인 의사결정은 사전 플랜, 플랜에 대한 복종과 끊임없는 분석으로 이루어진다. 이는 기계적인 의사결정으로도 볼 수 있다. 성공적인 의사결정을 위해서는 반드시 플랜이 있어야 한다. 그리고 플랜은 구체적인 진입과 탈출 규칙이 있어야 한다. 특히 탈출 규칙이 없다면 해당 플랜은 아무 의미가 없다.

플랜을 만들고, 철저히 지키고, 사후적으로 분석을 더한다고 해도 플랜은 절대 성공적인 의사결정을 않는다. 성공적인 플랜은 제한된 손실 만을 보장한다. 플랜은 손실을 제한함으로써 지속(continuous) 게임인 투자에서 투자자가 시장에 오래 남아 계속해서 게임에 참여할 수 있도록 한다.

시장이 왜 오르는지, 왜 내리는지 알아도 돈을 잃을 수 있다. 계획이 없다면 모든 움직임을 내재화 하면서 감정적인 결정을 내리면서 결국 심리적인 요인으로 돈을 잃게 될 것이다. 그래서 반드시 구체적인 탈출 규칙을 가진 계획을 가질 때만 시장에 포지션을 가지고 있어야 한다.

투자와 사업은 비슷한 면을 갖는다. 굉장히 다양한 요소가 작용해서 상승과 하락을 결정하고, 모든 과정이 의사결정 과정이며, 성공적인 의사결정을 위해서는 반드시 플랜이 있어야 한다. 그리고 한 순간의 성공 또는 실패를 내재화 하는 순간 모든 의사결정 과정은 감정적 의사결정으로 변하게 된다. 한 순간의 움직임은 그저 과정일 뿐, 절대 실패나 성공을 내재화 하지 마라.

투자와 사업에서 성공하는(돈을 버는) 방법은 수도 없이 많고 다양하다. 하지만 실패하는 방법은 단 하나다. 성공적인 의사결정을 위한 플랜을 세우지 않아 모든 현상(결과)를 내재화하고, 감정적인 의사결정이 반복되면서 제어되지 못한 손실이 쌓이면서 실패한다.

투자에서는 성공은 오로지 돈을 버느냐, 잃느냐에 달려있다. 중요한 건 왜 돈을 벌었는지, 왜 돈을 잃었는지 모른다면, 이는 반드시 감정적 의사결정으로 이어지고 파멸적인 결과를 맞이하게 된다는 것이다.

> “Broadly speaking, the decision-making process is as follows: (1) Decide what type of participant you’re going to be, (2) select a method of analysis, (3) develop rules, (4) establish controls, and (5) formulate a plan. Depending on what your goals or objectives are on the continuum of conservative to aggressive, you will decide whether you are an investor or speculator, which in turn will help you decide what markets to participate in, what method of analysis you’ll use, what rules you’ll develop, what controls you’ll have, and how you will implement these things with a plan. We already know that no single analytical method will be successful for everyone.”
> 

> “Remember, participating in the markets is about making decisions, and as Drucker reminds us, “There is no perfect decision. One always has to pay a price which might mean passing up an opportunity.””
> 

> “you can’t calculate the probability of a trade’s being profitable; you can only calculate your exposure. So all you can do is manage your losses, not predict profits.”
> 

> “Remember, there are as many ways to make money in the markets as there are participants. There are also as many possible plans as there are participants, yet only one valid recipe for formulating a plan.”
> 

> “Regardless of the methodology used, before you decide to get into the market you have to decide where (price) or when (time) or why (new information) you will no longer want the position.”
> 

> “to be effective as a loss-control tool, the plan must be derived by deciding STOP, ENTRY, then PRICE OBJECTIVE.”
> 

> “Knowing why doesn’t get you any brownie points with the market. Nor do you get any partial credit like you did in school for knowing why you got a math question wrong. And this is true for all business, not just the markets.”
> 

> “So you can be right and lose money. But which is more important? Remember, there are two kinds of reward in the world: recognition and money. Are you being motivated by the prophet motive or the profit motive? In the markets and in business don’t concern yourself with being right. Instead, follow your plan and watch the money.”
> 

> “Preoccupation with being right means you’re betting, which personalizes the market and is the root of losses due to psychological factors. Concern yourself with whether you have done your homework to define a set of conditions under which you will enter and exit the market and whether you carry out that plan.”
> 

> “As my mom used to say, “Weak is he who allows his actions to be controlled by his emotions, and strong is he who forces his actions to control his emotions.””
> 

> “Since your timing will in all likelihood never be perfect, the market would have been against you at some point, providing you plenty of opportunity to make an emotional decision and lose money. You must have a means to remove yourself from “subjectively experiencing” the market while making decisions.”
> 

> “All effective decision making requires maintaining one’s objectivity through the use of a plan, regardless of the type of decision being made.”
> 

> “In his book Teaching Thinking, internationally renowned education expert Edward de Bono says, “A person will use his thinking to keep himself right. This is especially true with more able pupils whose ego has been built up over the years on the basis that they are brighter than other pupils. Thinking is no longer used as an exploration of the subject area but as an ego support device.””
> 

> “When people personalize a string of successes (or profits) and an unfolding failure (or loss) develops, having come to believe they are infallible, they use all their intelligence as an ego-support device to prove that they are right, rather than as a means to determine an appropriate course of action.”
> 

> “When people personalize losses, they use their thinking to protect themselves, thereby rationalizing holding onto the position and distorting facts to support their view that they are “right,” not “wrong.””
> 

> “Remember, participating in the markets is not about egos and being right or wrong (i.e., opinions and betting), and it’s not about entertainment (i.e., excitement and gambling). Participating in the markets is about making money; it’s about decision making implemented by a plan. And if implemented properly, it’s actually quite boring waiting for your buy/ sell criteria to materialize. The minute it starts getting exciting, you are gambling.”
> 

> “Remember, Edison didn’t take the failures or losses personally, and he succeeded brilliantly (no pun intended). If, unlike Edison, you take the failures personally or, like Henry Ford, you take the successes personally, you are setting yourself up for disaster.”
> 

> “Having and following a plan doesn’t guarantee success, nor does it make you infallible. However, a plan is necessary for consistent loss control.”
> 

> “Take the loss, and don’t worry about it. Sticking to the discipline of your plan enables you to stay when you have a good situation and forces you to forfeit the ante when you don’t. If you drop your discipline and try bluffing, you’re exposing yourself to losing all of your money.”
> 

> “If you don’t know what is making the profitable trades profitable, you won’t know what to repeat in order to repeat the profits (or avoid losses). Your profits won’t be linked to any specific behavior on your part. This means you’re only going to be allowed to make a bad decision once—and you know you will do it at least once. You don’t know if it will be this time, next time, or the time after that. But you will do it. And if you bluff, you will lose your money.”
> 

> “We all know we shouldn’t smoke; a lot of us still do. We know we shouldn’t drink; a lot of us still do. We know we shouldn’t drive over the speed limit; a lot of us do. Why do we do all these things that are not good for us and that we know are not good for us? Well, because they feel good.” (...) “When it comes to the markets you’re supposed to do what feels good.”
> 

> “There is an inverse relationship between your threshold of pain and success in the markets, so as soon as you feel the pain: get out.”
> 

> “Goizueta didn’t personalize his previous successes, so he was able to recognize and accept the “loss.” He didn’t make the matter an issue of personal pride and choose to fight to the bitter end. He recognized it as a losing proposition to eliminate the original formula altogether. He cut his losses and moved on.”
> 

> “Remember, you don’t get any money just because you know why the market is going up or down. You only get money if your plan has positioned you to capitalize on the market’s movement, regardless of whether you know why the market is up or down on a particular day.”
> 

> “What’s true about the markets is also true for business in general. Just as there are many ways to make money in the markets, there are many ways to make money in business.”
> 

> “There is no single pattern to how the most successful entrepreneurs or the best managers in business make money. However, there is a common denominator among this group: rather than just taking risks, as is commonly assumed, they excel at judging, minimizing, and controlling risks.”
> 

> “It is important to understand that they held on not because they wanted to look good, look smart, or be right. They held on because the position remained within previously defined and acceptable loss parameters. Remember, people participate in the markets—all markets—either to satisfy a need (i.e., solve a problem) or to satisfy a want (i.e., make them feel good). Managing risk solves a problem and should never be engaged in to feel good, look smart, or be right.”
> 

> “As An Wang, founder of Wang Laboratories, said, “It is my belief that there are no ‘secrets’ to success.” 19 The formula for failure is not lack of knowledge, brains, skill, or hard work, and it’s not lack of luck; it’s personalizing losses, especially if preceded by a string of wins or profits. It’s refusing to acknowledge and accept the reality of a loss when it starts to occur because to do so would reflect negatively on you.”
>